In [1]:
import pandas as pd

In [ ]:
from get_lead_url import custome_run_scrapper

In [3]:
df = pd.read_csv("/home/shoarya/Desktop/leadomator/app/data/main_lead.csv")
df

                     Business
0                  restaurant
1                        cafe
2                         bar
3                         pub
4                      bakery
..                        ...
102        publishing service
103  video production company
104              music school
105             dance academy
106                art school

[107 rows x 1 columns]

In [4]:
df= df.head(100)

In [5]:
df

               Business
0            restaurant
1                  cafe
2                   bar
3                   pub
4                bakery
..                  ...
95  bookkeeping service
96       notary service
97      insurance agent
98          loan agency
99            pawn shop

[100 rows x 1 columns]

In [6]:
query = [ i+" in jodhpur" for i in df['Business']]
query

['restaurant in jodhpur',
 'cafe in jodhpur',
 'bar in jodhpur',
 'pub in jodhpur',
 'bakery in jodhpur',
 'fast food restaurant in jodhpur',
 'cloud kitchen in jodhpur',
 'catering service in jodhpur',
 'food delivery service in jodhpur',
 'e-commerce store in jodhpur',
 'online store in jodhpur',
 'clothing store in jodhpur',
 'jewelry store in jodhpur',
 'furniture store in jodhpur',
 'electronics store in jodhpur',
 'mobile phone shop in jodhpur',
 'computer store in jodhpur',
 'cosmetics store in jodhpur',
 'shoe store in jodhpur',
 'gift shop in jodhpur',
 'fitness center in jodhpur',
 'gym in jodhpur',
 'yoga studio in jodhpur',
 'beauty salon in jodhpur',
 'hair salon in jodhpur',
 'barber shop in jodhpur',
 'nail salon in jodhpur',
 'spa in jodhpur',
 'massage center in jodhpur',
 'photography studio in jodhpur',
 'videography service in jodhpur',
 'event planner in jodhpur',
 'wedding planner in jodhpur',
 'travel agency in jodhpur',
 'tour operator in jodhpur',
 'real estate agent in jodhpur',
 'property management company in jodhpur',
 'coaching institute in jodhpur',
 'online coaching in jodhpur',
 'coding institute in jodhpur',
 'language institute in jodhpur',
 'test preparation center in jodhpur',
 'digital marketing agency in jodhpur',
 'advertising agency in jodhpur',
 'branding agency in jodhpur',
 'pharmacy in jodhpur',
 'medical clinic in jodhpur',
 'dental clinic in jodhpur',
 'veterinary clinic in jodhpur',
 'interior designer in jodhpur',
 'architect in jodhpur',
 'construction company in jodhpur',
 'contractor in jodhpur',
 'plumber in jodhpur',
 'electrician in jodhpur',
 'home renovation service in jodhpur',
 'repair service in jodhpur',
 'maintenance service in jodhpur',
 'computer repair shop in jodhpur',
 'mobile repair shop in jodhpur',
 'printing shop in jodhpur',
 'signage company in jodhpur',
 'packaging service in jodhpur',
 'courier service in jodhpur',
 'logistics company in jodhpur',
 'import export company in jodhpur',
 'private school in jodhpur',
 'technical school in jodhpur',
 'training center in jodhpur',
 'tutoring service in jodhpur',
 'child care center in jodhpur',
 'non profit organization in jodhpur',
 'car rental service in jodhpur',
 'bike rental service in jodhpur',
 'car wash in jodhpur',
 'auto repair shop in jodhpur',
 'used car dealer in jodhpur',
 'new car showroom in jodhpur',
 'florist in jodhpur',
 'cleaning service in jodhpur',
 'pest control service in jodhpur',
 'landscaping service in jodhpur',
 'laundry service in jodhpur',
 'dry cleaning in jodhpur',
 'pet grooming in jodhpur',
 'pet boarding in jodhpur',
 'animal clinic in jodhpur',
 'funeral service in jodhpur',
 'cemetery service in jodhpur',
 'security service in jodhpur',
 'security system provider in jodhpur',
 'locksmith in jodhpur',
 'private investigator in jodhpur',
 'tax consultant in jodhpur',
 'accountant in jodhpur',
 'bookkeeping service in jodhpur',
 'notary service in jodhpur',
 'insurance agent in jodhpur',
 'loan agency in jodhpur',
 'pawn shop in jodhpur']

In [10]:
data =await custome_run_scrapper(query=query[0:10])

restaurant in jodhpur
                        title  \
0       NH RESTAURANT JODHPUR
1             House of Arches
2          Jeemann Restaurant
3  The Plant Story Restaurant
4              O High Jodhpur

                                                link
0  https://www.google.com/maps/place/NH+RESTAURAN...
1  https://www.google.com/maps/place/House+of+Arc...
2  https://www.google.com/maps/place/Jeemann+Rest...
3  https://www.google.com/maps/place/The+Plant+St...
4  https://www.google.com/maps/place/O+High+Jodhp...
title count: 60, link count: 60
end of the scrapping process times: -  1
cafe in jodhpur
                                               title  \
0                                      DinSun's Cafe
1                               Cafe Laalten Jodhpur
2                      The Heartland Cafe And Lounge
3                                        Casa blanca
4  The Almond Grove | Best Cafe & Restaurant in J...

                                                link
0  https://www.google.com/maps/place/DinSun%27s+C...
1  https://www.google.com/maps/place/Cafe+Laalten...
2  https://www.google.com/maps/place/The+Heartlan...
3  https://www.google.com/maps/place/Casa+blanca/...
4  https://www.google.com/maps/place/The+Almond+G...
title count: 80, link count: 80
end of the scrapping process times: -  2
bar in jodhpur
                                               title  \
0  Cocktails & More Lounge And Bar - Fairfield by...
1                                      The Beer Cafe
2                                    Velvet vine bar
3                                        Monarch Bar
4                                  ROYAL BAR JODHPUR

                                                link
0  https://www.google.com/maps/place/Cocktails+%2...
1  https://www.google.com/maps/place/The+Beer+Caf...
2  https://www.google.com/maps/place/Velvet+vine+...
3  https://www.google.com/maps/place/Monarch+Bar/...
4  https://www.google.com/maps/place/ROYAL+BAR+JO...
title count: 120, link count: 120
end of the scrapping process times: -  3
pub in jodhpur
                                               title  \
0                              The Checkers Club 2.0
1                                GEOFFREY'S- THE PUB
2                                      The Beer Cafe
3  Cocktails & More Lounge And Bar - Fairfield by...
4  Four Brothers Brewing - Restrobar | Club | Mic...

                                                link
0  https://www.google.com/maps/place/The+Checkers...
1  https://www.google.com/maps/place/GEOFFREY%27S...
2  https://www.google.com/maps/place/The+Beer+Caf...
3  https://www.google.com/maps/place/Cocktails+%2...
4  https://www.google.com/maps/place/Four+Brother...
title count: 102, link count: 102
end of the scrapping process times: -  4
bakery in jodhpur
                                               title  \
0   Queen's Bakery - Gluten free products in jodhpur
1  Bake N Bite Bakery bakery in tulsi tower Shard...
2                        15 A.D. Bakery - Sardarpura
3                           Ever Fresh Cake N Bakers
4                                     Innings Bakery

                                                link
0  https://www.google.com/maps/place/Queen%27s+Ba...
1  https://www.google.com/maps/place/Bake+N+Bite+...
2  https://www.google.com/maps/place/15+A.D.+Bake...
3  https://www.google.com/maps/place/Ever+Fresh+C...
4  https://www.google.com/maps/place/Innings+Bake...
title count: 100, link count: 100
end of the scrapping process times: -  5
fast food restaurant in jodhpur
                                         title  \
0  Jodhpur Veg, Non-Veg & Fast Food Restaurant
1                                CPG Fast Food
2     Fun N Food - Pure Veg. Family Restaurant
3                   SARDAR JI RESTAURANT {SJR}
4                            Chouhan Fast Food

                                                link
0  https://www.google.com/maps/place/Jodhpur+Veg,...
1  https://www.google.com/maps/place/CPG+Fast+Foo...
2  https://www.google.com/maps/place/Fun+N+Food+-...
3  https://www.google.com/maps/place/SARDAR+JI+RE...
4  https://www.google.com/maps/place/Chouhan+Fast...
title count: 120, link count: 120
end of the scrapping process times: -  6
cloud kitchen in jodhpur
                           title  \
0   The Bon Viveur Cloud Kitchen
1    Shree Vinayak Cloud kitchen
2     DE BABU BHAI CLOUD KITCHEN
3                  Cloud Kitchen
4  HAFLONG CLOUD KITCHEN JODHPUR

                                                link
0  https://www.google.com/maps/place/The+Bon+Vive...
1  https://www.google.com/maps/place/Shree+Vinaya...
2  https://www.google.com/maps/place/DE+BABU+BHAI...
3  https://www.google.com/maps/place/Cloud+Kitche...
4  https://www.google.com/maps/place/HAFLONG+CLOU...
title count: 37, link count: 37
end of the scrapping process times: -  7
catering service in jodhpur
                                    title  \
0               Rajshree catering service
1                               MRS FOODS
2  Parihar Catering | Caterers in jodhpur
3                 Vaishnav tiffin service
4                           Amar Caterers

                                                link
0  https://www.google.com/maps/place/Rajshree+cat...
1  https://www.google.com/maps/place/MRS+FOODS/da...
2  https://www.google.com/maps/place/Parihar+Cate...
3  https://www.google.com/maps/place/Vaishnav+tif...
4  https://www.google.com/maps/place/Amar+Caterer...
title count: 40, link count: 40
end of the scrapping process times: -  8
food delivery service in jodhpur
                                         title  \
0                                    MRS FOODS
1                      Vaishnav tiffin service
2  Jodhpur Veg, Non-Veg & Fast Food Restaurant
3                          Maa Gajan Fast Food
4                            1952 A Food Story

                                                link
0  https://www.google.com/maps/place/MRS+FOODS/da...
1  https://www.google.com/maps/place/Vaishnav+tif...
2  https://www.google.com/maps/place/Jodhpur+Veg,...
3  https://www.google.com/maps/place/Maa+Gajan+Fa...
4  https://www.google.com/maps/place/1952+A+Food+...
title count: 108, link count: 108
end of the scrapping process times: -  9
e-commerce store in jodhpur
                                               title  \
0  Teckey Digital Solutions | Best Digital Market...
1                           Ecommerce work solutions
2                                   Reliance Digital
3                      Click400 Technologies Pvt Ltd
4               Digital Marketing Company In Jodhpur

                                                link
0  https://www.google.com/maps/place/Teckey+Digit...
1  https://www.google.com/maps/place/Ecommerce+wo...
2  https://www.google.com/maps/place/Reliance+Dig...
3  https://www.google.com/maps/place/Click400+Tec...
4  https://www.google.com/maps/place/Digital+Mark...
title count: 96, link count: 96
end of the scrapping process times: -  10

In [11]:
data.head()

,Title,Link,title,link
0,NaN,NaN,NH RESTAURANT JODHPUR,https://www.google.com/maps/place/NH+RESTAURAN...
1,NaN,NaN,House of Arches,https://www.google.com/maps/place/House+of+Arc...
2,NaN,NaN,Jeemann Restaurant,https://www.google.com/maps/place/Jeemann+Rest...
3,NaN,NaN,The Plant Story Restaurant,https://www.google.com/maps/place/The+Plant+St...
4,NaN,NaN,O High Jodhpur,https://www.google.com/maps/place/O+High+Jodhp...

In [12]:
data

,Title,Link,title,link
0,NaN,NaN,NH RESTAURANT JODHPUR,https://www.google.com/maps/place/NH+RESTAURAN...
1,NaN,NaN,House of Arches,https://www.google.com/maps/place/House+of+Arc...
2,NaN,NaN,Jeemann Restaurant,https://www.google.com/maps/place/Jeemann+Rest...
3,NaN,NaN,The Plant Story Restaurant,https://www.google.com/maps/place/The+Plant+St...
4,NaN,NaN,O High Jodhpur,https://www.google.com/maps/place/O+High+Jodhp...
...,...,...,...,...
694,NaN,NaN,MetStore's,https://www.google.com/maps/place/MetStore%27s...
695,NaN,NaN,SKdigiSkill - Digital Marketing Agency In Jodhpur,https://www.google.com/maps/place/SKdigiSkill+...
696,NaN,NaN,MV SPICES (Mohanlal Verhomal),https://www.google.com/maps/place/MV+SPICES+%2...
697,NaN,NaN,Singhal Electronics,https://www.google.com/maps/place/Singhal+Elec...
698,NaN,NaN,Krishna computer: computer dealers in jodhpur.,https://www.google.com/maps/place/Krishna+comp...

In [13]:
new_data = pd.DataFrame()

In [14]:
new_data['Title'] = data['title']

In [15]:
new_data

                                                 Title
0                                NH RESTAURANT JODHPUR
1                                      House of Arches
2                                   Jeemann Restaurant
3                           The Plant Story Restaurant
4                                       O High Jodhpur
..                                                 ...
694                                         MetStore's
695  SKdigiSkill - Digital Marketing Agency In Jodhpur
696                      MV SPICES (Mohanlal Verhomal)
697                                Singhal Electronics
698     Krishna computer: computer dealers in jodhpur.

[699 rows x 1 columns]

In [40]:
new_data['Link'] = data['link']
new_data.rename(columns={"Link": 'url'},inplace=True)
new_data.index.name = "id"
new_data.reset_index(inplace=True)

In [41]:
new_data

,id,Title,url,url,url,url
0,0,NH RESTAURANT JODHPUR,https://www.google.com/maps/place/NH+RESTAURAN...,https://www.google.com/maps/place/NH+RESTAURAN...,https://www.google.com/maps/place/NH+RESTAURAN...,https://www.google.com/maps/place/NH+RESTAURAN...
1,1,House of Arches,https://www.google.com/maps/place/House+of+Arc...,https://www.google.com/maps/place/House+of+Arc...,https://www.google.com/maps/place/House+of+Arc...,https://www.google.com/maps/place/House+of+Arc...
2,2,Jeemann Restaurant,https://www.google.com/maps/place/Jeemann+Rest...,https://www.google.com/maps/place/Jeemann+Rest...,https://www.google.com/maps/place/Jeemann+Rest...,https://www.google.com/maps/place/Jeemann+Rest...
3,3,The Plant Story Restaurant,https://www.google.com/maps/place/The+Plant+St...,https://www.google.com/maps/place/The+Plant+St...,https://www.google.com/maps/place/The+Plant+St...,https://www.google.com/maps/place/The+Plant+St...
4,4,O High Jodhpur,https://www.google.com/maps/place/O+High+Jodhp...,https://www.google.com/maps/place/O+High+Jodhp...,https://www.google.com/maps/place/O+High+Jodhp...,https://www.google.com/maps/place/O+High+Jodhp...
...,...,...,...,...,...,...
694,694,MetStore's,https://www.google.com/maps/place/MetStore%27s...,https://www.google.com/maps/place/MetStore%27s...,https://www.google.com/maps/place/MetStore%27s...,https://www.google.com/maps/place/MetStore%27s...
695,695,SKdigiSkill - Digital Marketing Agency In Jodhpur,https://www.google.com/maps/place/SKdigiSkill+...,https://www.google.com/maps/place/SKdigiSkill+...,https://www.google.com/maps/place/SKdigiSkill+...,https://www.google.com/maps/place/SKdigiSkill+...
696,696,MV SPICES (Mohanlal Verhomal),https://www.google.com/maps/place/MV+SPICES+%2...,https://www.google.com/maps/place/MV+SPICES+%2...,https://www.google.com/maps/place/MV+SPICES+%2...,https://www.google.com/maps/place/MV+SPICES+%2...
697,697,Singhal Electronics,https://www.google.com/maps/place/Singhal+Elec...,https://www.google.com/maps/place/Singhal+Elec...,https://www.google.com/maps/place/Singhal+Elec...,https://www.google.com/maps/place/Singhal+Elec...
698,698,Krishna computer: computer dealers in jodhpur.,https://www.google.com/maps/place/Krishna+comp...,https://www.google.com/maps/place/Krishna+comp...,https://www.google.com/maps/place/Krishna+comp...,https://www.google.com/maps/place/Krishna+comp...

In [54]:
print(new_data[new_data["id"] == 197])

      id   Title                                                url  \
197  197  ₹1,534  https://www.google.com/maps/place/Hotel+Shri+R...

                                                   url  \
197  https://www.google.com/maps/place/Hotel+Shri+R...

                                                   url  \
197  https://www.google.com/maps/place/Hotel+Shri+R...

                                                   url
197  https://www.google.com/maps/place/Hotel+Shri+R...

In [42]:
from get_main_main_data import main

In [44]:
URLS = new_data[["id", "url"]].dropna().values.tolist()
res = await main(CONCURRENT_PAGES=10, URLS=URLS[1:200])

[
    {
        "id": 1,
        "url": "https://www.google.com/maps/place/House+of+Arches/data=!4m7!3m6!1s0x394189ff6d264b6b:0xa707a9092556bcfd!8m2!3d26.2189887!4d72.9791311!16s%2Fg%2F11vbv0cjcs!19sChIJa0smbf-JQTkR_bxWJQmpB6c?authuser=0&hl=en&rclk=1",
        "phone": "09414100102",
        "rating": "4.8"
    },
    {
        "id": 2,
        "url": "https://www.google.com/maps/place/Jeemann+Restaurant/data=!4m7!3m6!1s0x39418b1011ecb3bf:0x2d9f39d7c848a769!8m2!3d26.2134608!4d73.0222376!16s%2Fg%2F11ffm38dc_!19sChIJv7PsERCLQTkRaadIyNc5ny0?authuser=0&hl=en&rclk=1",
        "phone": "07976085653",
        "rating": "4.2"
    },
    {
        "id": 3,
        "url": "https://www.google.com/maps/place/The+Plant+Story+Restaurant/data=!4m7!3m6!1s0x39418d244effef09:0xd7a6df821524706b!8m2!3d26.2819051!4d73.0048006!16s%2Fg%2F11mw8l6vmd!19sChIJCe__TiSNQTkRa3AkFYLfptc?authuser=0&hl=en&rclk=1",
        "phone": "08989920000",
        "website": "https://theplantstory.co.in/",
        "rating": "4.5"
    },
    {
        "id": 4,
        "url": "https://www.google.com/maps/place/O+High+Jodhpur/data=!4m7!3m6!1s0x39418dd8427d29d3:0x86839c32bc0163ab!8m2!3d26.2499201!4d72.9788011!16s%2Fg%2F11vrzls2xp!19sChIJ0yl9QtiNQTkRq2MBvDKcg4Y?authuser=0&hl=en&rclk=1",
        "phone": "09116952516",
        "website": "https://www.swiggy.com/restaurants/o-high-keshavnagar-koramangala-jodhpur-1336281/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.8"
    },
    {
        "id": 5,
        "url": "https://www.google.com/maps/place/Maa+Ki+Dhani+%28%E0%A4%AE%E0%A4%BE%E0%A4%81+%E0%A4%95%E0%A5%80+%E0%A4%A2%E0%A4%BE%E0%A4%A3%E0%A5%80%29/data=!4m7!3m6!1s0x39418b6950582477:0x9893257857f791f9!8m2!3d26.2344965!4d73.0180081!16s%2Fg%2F11vx0kh6nf!19sChIJdyRYUGmLQTkR-ZH3V3glk5g?authuser=0&hl=en&rclk=1",
        "phone": "09929119295",
        "website": "https://maakidhani.in/",
        "rating": "4.7"
    },
    {
        "id": 6,
        "url": "https://www.google.com/maps/place/The+Grand+Turf+Pure+Vegetarian+Family+Restaurant/data=!4m7!3m6!1s0x39418b9fe0480753:0x249df01907b946aa!8m2!3d26.2207012!4d73.0414787!16s%2Fg%2F11gdy2hf1y!19sChIJUwdI4J-LQTkRqka5BxnwnSQ?authuser=0&hl=en&rclk=1",
        "phone": "09619319099",
        "website": "https://q-xx.bstatic.com/xdata/images/hotel/max1024x683/428978571.jpg?k\\u003d14e59b49319ebd00fb6528509fb0c06dd180f89b6f6891a41d674e719b67ff01\\u0026o\\u003d\\u0026a\\u003d1538557",
        "rating": "4.5"
    },
    {
        "id": 7,
        "url": "https://www.google.com/maps/place/Kesar+The+Restaurant/data=!4m7!3m6!1s0x39418b448e97ac67:0x5b6529a4ddc92e58!8m2!3d26.2194202!4d73.0264175!16s%2Fg%2F11stkm3f58!19sChIJZ6yXjkSLQTkRWC7J3aQpZVs?authuser=0&hl=en&rclk=1",
        "phone": "07878142153",
        "rating": "4.5"
    },
    {
        "id": 8,
        "url": "https://www.google.com/maps/place/The+Olive+Court/data=!4m7!3m6!1s0x39418d0baaf148c9:0x31d82d99bbb04b9e!8m2!3d26.2697989!4d73.0385446!16s%2Fg%2F11l6htfrds!19sChIJyUjxqguNQTkRnkuwu5kt2DE?authuser=0&hl=en&rclk=1",
        "phone": "08824519693",
        "website": "https://www.swiggy.com/restaurants/the-olive-court-ratanada-koramangala-jodhpur-969473/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.7"
    },
    {
        "id": 9,
        "url": "https://www.google.com/maps/place/1952+A+Food+Story/data=!4m7!3m6!1s0x39418d731e264fcd:0xa4a1c6ac53b09d15!8m2!3d26.2084376!4d73.0247331!16s%2Fg%2F11jsm85f_w!19sChIJzU8mHnONQTkRFZ2wU6zGoaQ?authuser=0&hl=en&rclk=1",
        "phone": "08112296803",
        "website": "https://www.swiggy.com/restaurants/1952-a-food-story-gopal-bari-basni-jodhpur-686791/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.8"
    },
    {
        "id": 10,
        "url": "https://www.google.com/maps/place/Indique+Restaurant+%26+Bar/data=!4m7!3m6!1s0x39418db72d475c51:0x7c10f67cc3d86d02!8m2!3d26.2963176!4d73.0239142!16s%2Fg%2F11b70g407m!19sChIJUVxHLbeNQTkRAm3Yw3z2EHw?authuser=0&hl=en&rclk=1",
        "phone": "09672293328",
        "website": "https://www.palhaveli.com/indiquerestaurant",
        "rating": "4.3"
    },
    {
        "id": 11,
        "url": "https://www.google.com/maps/place/THE+SPICE+STORY+II+BEST+VEGETARIAN+FAMILY+RESTAURANT+II+FINE+DINE+%26+ROOFTOP/data=!4m7!3m6!1s0x39418d1100aadcdb:0xba448337948070c8!8m2!3d26.2793265!4d73.0375348!16s%2Fg%2F11txlcncbj!19sChIJ29yqABGNQTkRyHCAlDeDRLo?authuser=0&hl=en&rclk=1",
        "phone": "09001890329",
        "website": "https://www.swiggy.com/restaurants/the-spice-story-ratanada-basni-jodhpur-913297/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.7"
    },
    {
        "id": 12,
        "url": "https://www.google.com/maps/place/Indigo+Restaurant/data=!4m7!3m6!1s0x39418db744033e3f:0x308e593b418fc2d5!8m2!3d26.2975992!4d73.0218181!16s%2Fg%2F11b6d4cfsd!19sChIJPz4DRLeNQTkR1cKPQTtZjjA?authuser=0&hl=en&rclk=1",
        "phone": "09829524809",
        "rating": "4.6"
    },
    {
        "id": 13,
        "url": "https://www.google.com/maps/place/Unaavu/data=!4m7!3m6!1s0x39418d9be9e31b8d:0x820427f902583eb4!8m2!3d26.267619!4d73.0396952!16s%2Fg%2F11t7z69j65!19sChIJjRvj6ZuNQTkRtD5YAvknBII?authuser=0&hl=en&rclk=1",
        "phone": "08824867154",
        "website": "https://www.swiggy.com/restaurants/unaavu-ratanada-new-jodhpur-jodhpur-645977/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.6"
    },
    {
        "id": 14,
        "url": "https://www.google.com/maps/place/Spicy+Table/data=!4m7!3m6!1s0x39418ba85299866d:0x8108d03980161675!8m2!3d26.227094!4d73.0394165!16s%2Fg%2F11ww8qhtqv!19sChIJbYaZUqiLQTkRdRYWgDnQCIE?authuser=0&hl=en&rclk=1",
        "phone": "08905460304",
        "rating": "4.5"
    },
    {
        "id": 15,
        "url": "https://www.google.com/maps/place/The+Flamingo/data=!4m7!3m6!1s0x39418def813c43e3:0xcfb5ffe749b2b3a6!8m2!3d26.2703777!4d73.0377509!16s%2Fg%2F11frlhmvts!19sChIJ40M8ge-NQTkRprOySef_tc8?authuser=0&hl=en&rclk=1",
        "phone": "07877573264",
        "website": "https://www.swiggy.com/restaurants/the-flamingo-ratanada-new-jodhpur-jodhpur-383652/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.6"
    },
    {
        "id": 16,
        "url": "https://www.google.com/maps/place/Bhootnath+Restaurant+%26+cafe/data=!4m7!3m6!1s0x39418d7b4637094b:0xc855848de9f0b4fd!8m2!3d26.2729449!4d73.0253689!16s%2Fg%2F11tnmb41zs!19sChIJSwk3RnuNQTkR_bTw6Y2EVcg?authuser=0&hl=en&rclk=1",
        "rating": "4.9"
    },
    {
        "id": 17,
        "url": "https://www.google.com/maps/place/Maverick+Jodhpur/data=!4m7!3m6!1s0x39418dc20e1e0081:0xccc2caa02b7e8799!8m2!3d26.2707051!4d73.03016!16s%2Fg%2F11lyxkbmjj!19sChIJgQAeDsKNQTkRmYd-K6DKwsw?authuser=0&hl=en&rclk=1",
        "phone": "08440908000",
        "website": "https://maverickjodhpur.com/",
        "rating": "4.6"
    },
    {
        "id": 18,
        "url": "https://www.google.com/maps/place/VYANJANAM/data=!4m7!3m6!1s0x39418dc55b387043:0x987018859e7e92f7!8m2!3d26.2773173!4d73.004203!16s%2Fg%2F11s5c_n_6t!19sChIJQ3A4W8WNQTkR95J-noUYcJg?authuser=0&hl=en&rclk=1",
        "phone": "07240100021",
        "rating": "4.7"
    },
    {
        "id": 19,
        "url": "https://www.google.com/maps/place/Kalinga+Restaurant/data=!4m7!3m6!1s0x39418c4b715e48d3:0xb8b9f9b29db318ab!8m2!3d26.2844136!4d73.0215372!16s%2Fg%2F11b6zpcd3l!19sChIJ00hecUuMQTkRqxiznbL5ubg?authuser=0&hl=en&rclk=1",
        "phone": "07300054888",
        "website": "https://www.swiggy.com/restaurants/kalinga-restaurant-ratanada-new-jodhpur-jodhpur-85757/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.2"
    },
    {
        "id": 20,
        "url": "https://www.google.com/maps/place/On+The+Rocks/data=!4m7!3m6!1s0x39418c565fb9169d:0x4d9b71f195878ac!8m2!3d26.2817423!4d73.0376391!16s%2Fg%2F1td9c4h_!19sChIJnRa5X1aMQTkRrHhYGR-32QQ?authuser=0&hl=en&rclk=1",
        "phone": "09119364555",
        "rating": "4.2"
    },
    {
        "id": 21,
        "url": "https://www.google.com/maps/place/Gopal+Roof+Top+Restaurant+%28+Rajsthani+Cuisine+%26+Lal+Maas+%29/data=!4m7!3m6!1s0x39418db72e828651:0xc56036a9188ddc0c!8m2!3d26.2964128!4d73.0222544!16s%2Fg%2F11h4s21zy4!19sChIJUYaCLreNQTkRDNyNGKk2YMU?authuser=0&hl=en&rclk=1",
        "phone": "09828230781",
        "website": "https://link.zomato.com/xqzv/rshare?id\\u003d19923423bdcb9b36",
        "rating": "4.6"
    },
    {
        "id": 22,
        "url": "https://www.google.com/maps/place/Jodhpur+Veg,+Non-Veg+%26+Fast+Food+Restaurant/data=!4m7!3m6!1s0x39418b772916c10b:0x4386c1efccbc07aa!8m2!3d26.2090485!4d73.0272835!16s%2Fg%2F11g30_q28t!19sChIJC8EWKXeLQTkRqge8zO_BhkM?authuser=0&hl=en&rclk=1",
        "phone": "08239640772",
        "rating": "3.9"
    },
    {
        "id": 23,
        "url": "https://www.google.com/maps/place/Acharya+Rooftop+Restaurant+%26+Guest+House/data=!4m7!3m6!1s0x39418d637748c325:0x9da135c45a7add13!8m2!3d26.2981184!4d73.0211105!16s%2Fg%2F11tnnqbfq_!19sChIJJcNId2ONQTkRE916WsQ1oZ0?authuser=0&hl=en&rclk=1",
        "phone": "09024077490",
        "rating": "4.8"
    },
    {
        "id": 24,
        "url": "https://www.google.com/maps/place/Divyanshi+The+Taste+Of+Jodhpur+Veg-Non+Veg+Restaurant/data=!4m7!3m6!1s0x39418bcc3355a1a5:0xb6503b3beb38376d!8m2!3d26.2160158!4d73.0153581!16s%2Fg%2F11l5vh0cc_!19sChIJpaFVM8yLQTkRbTc46zs7ULY?authuser=0&hl=en&rclk=1",
        "phone": "09636533777",
        "website": "https://www.swiggy.com/restaurants/the-taste-of-jodhpur-meera-nagar-basni-jodhpur-799435/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.5"
    },
    {
        "id": 25,
        "url": "https://www.google.com/maps/place/Gypsy+Vegetarian+Restaurant/data=!4m7!3m6!1s0x39418d2be40d9b47:0xc82a0250d43fbf36!8m2!3d26.2751618!4d73.0077764!16s%2Fg%2F1td74zyg!19sChIJR5sN5CuNQTkRNr8_1FACKsg?authuser=0&hl=en&rclk=1",
        "phone": "07412074075",
        "rating": "4"
    },
    {
        "id": 26,
        "url": "https://www.google.com/maps/place/Kasturi+Flavours+Restaurant+-+Jodhpur/data=!4m7!3m6!1s0x39418938220cc6d3:0x8e9dd95f27abadad!8m2!3d26.2223226!4d72.9686233!16s%2Fg%2F11fzfbswy8!19sChIJ08YMIjiJQTkRra2rJ1_ZnY4?authuser=0&hl=en&rclk=1",
        "phone": "08094008357",
        "website": "https://www.kasturiorchid.com/our-restaurant/",
        "rating": "4.7"
    },
    {
        "id": 27,
        "url": "https://www.google.com/maps/place/Kava+Restaurant+And+Lounge+-+Fairfield+by+Marriott+Jodhpur/data=!4m7!3m6!1s0x39418ba8c4821ee5:0xd26c660eb4d42929!8m2!3d26.2172753!4d73.0448635!16s%2Fg%2F11hgp1lrg5!19sChIJ5R6CxKiLQTkRKSnUtA5mbNI?authuser=0&hl=en&rclk=1",
        "phone": "02917112222",
        "website": "https://www.marriott.com/hotels/hotel-information/restaurant/jdhfi-fairfield-jodhpur/",
        "rating": "4.1"
    },
    {
        "id": 28,
        "url": "https://www.google.com/maps/place/ON+THE+FARM+%28OTF%29/data=!4m7!3m6!1s0x39418df1046db9e3:0xa9ec373a9c91c269!8m2!3d26.2644886!4d73.0593399!16s%2Fg%2F11qh2wqsr1!19sChIJ47ltBPGNQTkRacKRnDo37Kk?authuser=0&hl=en&rclk=1",
        "phone": "07014295011",
        "rating": "4.2"
    },
    {
        "id": 29,
        "url": "https://www.google.com/maps/place/Rigveda%E2%80%99+Jodhpur/data=!4m7!3m6!1s0x39418c46dea1c0cd:0x7d5412512b88e751!8m2!3d26.2708648!4d73.0201595!16s%2Fg%2F11cnb89xpl!19sChIJzcCh3kaMQTkRUeeIK1ESVH0?authuser=0&hl=en&rclk=1",
        "phone": "09314784000",
        "website": "https://www.swiggy.com/restaurants/rigveda-ratanada-basni-jodhpur-866880/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.4"
    },
    {
        "id": 30,
        "url": "https://www.google.com/maps/place/Hari+Vedas%27+Jodhpur/data=!4m7!3m6!1s0x39418c307664eaf9:0x2c7c6b5a19c2c869!8m2!3d26.2741545!4d73.0070067!16s%2Fg%2F11b67f3frf!19sChIJ-epkdjCMQTkRacjCGVprfCw?authuser=0&hl=en&rclk=1",
        "phone": "02912444444",
        "website": "https://www.swiggy.com/restaurants/hari-vedas-sardarpura-basni-jodhpur-866802/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.2"
    },
    {
        "id": 31,
        "url": "https://www.google.com/maps/place/Vegetrainian+-+The+Train+Restaurant/data=!4m7!3m6!1s0x39418d472a9ddfdb:0xc94c978068428e5e!8m2!3d26.2665463!4d73.0235491!16s%2Fg%2F11h4pcb9cq!19sChIJ29-dKkeNQTkRXo5CaICXTMk?authuser=0&hl=en&rclk=1",
        "phone": "08905005600",
        "website": "https://www.swiggy.com/restaurants/vegetrainian-the-train-restaurant-sardarpura-new-jodhpur-jodhpur-513288/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.3"
    },
    {
        "id": 32,
        "url": "https://www.google.com/maps/place/Ricotta/data=!4m7!3m6!1s0x39418d0538500a97:0xc7ce032f95befc7e!8m2!3d26.2713891!4d73.0081135!16s%2Fg%2F11krhm6t16!19sChIJlwpQOAWNQTkRfvy-lS8Dzsc?authuser=0&hl=en&rclk=1",
        "phone": "09352197529",
        "website": "https://www.swiggy.com/restaurants/ricotta-shastri-nagar-koramangala-jodhpur-1055698/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.7"
    },
    {
        "id": 33,
        "url": "https://www.google.com/maps/place/Shree+Subhadra+hotel+$+family+restaurant/data=!4m7!3m6!1s0x39418bbcac3497df:0x3e7ea7eadf40c821!8m2!3d26.2138014!4d73.0285518!16s%2Fg%2F1hm22vqtd!19sChIJ35c0rLyLQTkRIchA3-qnfj4?authuser=0&hl=en&rclk=1",
        "phone": "09829611960",
        "rating": "4.1"
    },
    {
        "id": 34,
        "url": "https://www.google.com/maps/place/SAGA/data=!4m7!3m6!1s0x39418db7167277d9:0x599558aa5c4460d4!8m2!3d26.2708205!4d73.0302959!16s%2Fg%2F11h80dw6sx!19sChIJ2XdyFreNQTkR1GBEXKpYlVk?authuser=0&hl=en&rclk=1",
        "phone": "08824688830",
        "website": "https://www.swiggy.com/restaurants/saga-ratanada-new-jodhpur-jodhpur-548990/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.6"
    },
    {
        "id": 35,
        "url": "https://www.google.com/maps/place/Bungalow+12/data=!4m7!3m6!1s0x39418dde1e2a49d7:0x3b1c3e7d5b012df4!8m2!3d26.2675243!4d73.0309974!16s%2Fg%2F11nxqyxdrl!19sChIJ10kqHt6NQTkR9C0BW30-HDs?authuser=0&hl=en&rclk=1",
        "phone": "09828561212",
        "website": "https://www.instagram.com/bungalow.twelve/",
        "rating": "4.4"
    },
    {
        "id": 36,
        "url": "https://www.google.com/maps/place/The+Big+%22O%22+Restaurant+and+Lounge/data=!4m7!3m6!1s0x39418fe00fab856b:0x6ba5c8f3c44d6a76!8m2!3d26.2449574!4d72.9737318!16s%2Fg%2F11fsk9k4wq!19sChIJa4WrD-CPQTkRdmpNxPPIpWs?authuser=0&hl=en&rclk=1",
        "phone": "07568502020",
        "website": "https://www.swiggy.com/restaurants/the-big-o-restaurant-and-lounge-near-hp-petrol-pump-west-jodhpur-jodhpur-686551/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.1"
    },
    {
        "id": 37,
        "url": "https://www.google.com/maps/place/Haldi+Restaurant+%26+Banquet+Hall/data=!4m7!3m6!1s0x39418b7e0e0353e7:0xfe37b017b732c148!8m2!3d26.2370208!4d73.0100165!16s%2Fg%2F11sfbtw6r_!19sChIJ51MDDn6LQTkRSMEytxewN_4?authuser=0&hl=en&rclk=1",
        "phone": "08769238369",
        "website": "https://www.zomato.com/jodhpur/haldi-restaurant-basni",
        "rating": "4.4"
    },
    {
        "id": 38,
        "url": "https://www.google.com/maps/place/Gazania+Restaurant/data=!4m7!3m6!1s0x39418d4ca1581d11:0x6731e7c01fbb87d2!8m2!3d26.2765089!4d73.0347203!16s%2Fg%2F11tdnk47gr!19sChIJER1YoUyNQTkR0oe7H8DnMWc?authuser=0&hl=en&rclk=1",
        "phone": "07300009192",
        "rating": "4.1"
    },
    {
        "id": 39,
        "url": "https://www.google.com/maps/place/Pet+Pooja+Veg+%26+Non-veg+restaurant/data=!4m7!3m6!1s0x39418b1bff20e36b:0x5ec827d0c561c0fd!8m2!3d26.2082163!4d73.025086!16s%2Fg%2F11rqxsf50r!19sChIJa-Mg_xuLQTkR_cBhxdAnyF4?authuser=0&hl=en&rclk=1",
        "phone": "08003802957",
        "rating": "5"
    },
    {
        "id": 40,
        "url": "https://www.google.com/maps/place/ZEEMLOGY+RESTAURANT/data=!4m7!3m6!1s0x39418d5e9c83aed1:0x7e21007009709f1a!8m2!3d26.2771007!4d73.0328628!16s%2Fg%2F11vdzvw6wc!19sChIJ0a6DnF6NQTkRGp9wCXAAIX4?authuser=0&hl=en&rclk=1",
        "phone": "09929672219",
        "website": "https://www.swiggy.com/restaurants/zeemlogy-restaurant-ratanada-koramangala-jodhpur-1129095/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.6"
    },
    {
        "id": 41,
        "url": "https://www.google.com/maps/place/DARBAARI+-+THE+INDIAN+GRILLS+II+BEST+NON+VEGETARIAN+RESTAURANT/data=!4m7!3m6!1s0x39418d000b0aec39:0xab8829ee69838410!8m2!3d26.2710068!4d73.0387964!16s%2Fg%2F11wg4zhwnt!19sChIJOewKCwCNQTkREISDae4piKs?authuser=0&hl=en&rclk=1",
        "website": "https://www.zomato.com/jodhpur/darbaari-the-indian-grills-1-ratanada/book?utm_source\\u003drwg",
        "rating": "4.5"
    },
    {
        "id": 42,
        "url": "https://www.google.com/maps/place/THE+SOLO+HOUSE+RESTAURANT/data=!4m7!3m6!1s0x39418d001fdaf791:0x2fb039ccff4d1f7e!8m2!3d26.2712082!4d73.0291063!16s%2Fg%2F11m64vsc28!19sChIJkffaHwCNQTkRfh9N_8w5sC8?authuser=0&hl=en&rclk=1",
        "phone": "08358005900",
        "website": "https://thesolohouseindia.com/",
        "rating": "4.8"
    },
    {
        "id": 43,
        "url": "https://www.google.com/maps/place/Shree+Balaji+Restaurant/data=!4m7!3m6!1s0x39418b0652df413f:0x220d9c6dce23d1b7!8m2!3d26.205699!4d73.0151944!16s%2Fg%2F11k9jcxk6g!19sChIJP0HfUgaLQTkRt9Ejzm2cDSI?authuser=0&hl=en&rclk=1",
        "phone": "08290739066",
        "rating": "4.7"
    },
    {
        "id": 44,
        "url": "https://www.google.com/maps/place/Barbeque+On+Table/data=!4m7!3m6!1s0x39418ba59bde33bf:0x68dbfdc289912f62!8m2!3d26.2704395!4d73.0401234!16s%2Fg%2F11t2z0f4vg!19sChIJvzPem6WLQTkRYi-RicL922g?authuser=0&hl=en&rclk=1",
        "phone": "09521677773",
        "website": "https://www.swiggy.com/restaurants/barbeque-on-table-defence-lab-road-new-jodhpur-jodhpur-708012/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",
        "rating": "4.3"
    },
    {
        "id": 45,
        "url": "https://www.google.com/maps/place/Baari+restaurant/data=!4m7!3m6!1s0x39418da60e04df95:0xbe0cbc41916e80b4!8m2!3d26.3011601!4d73.0353292!16s%2Fg%2F11c31pn5_h!19sChIJld8EDqaNQTkRtIBukUG8DL4?authuser=0&hl=en&rclk=1",
        "phone": "09660059488",
        "website": "https://www.swiggy.com/restaurants/baari-restaurant-and-lounge-paota-koramangala-jodhpur-1070904/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve",

In [45]:
res

[{'id': 1,
  'url': 'https://www.google.com/maps/place/House+of+Arches/data=!4m7!3m6!1s0x394189ff6d264b6b:0xa707a9092556bcfd!8m2!3d26.2189887!4d72.9791311!16s%2Fg%2F11vbv0cjcs!19sChIJa0smbf-JQTkR_bxWJQmpB6c?authuser=0&hl=en&rclk=1',
  'phone': '09414100102',
  'rating': '4.8'},
 {'id': 2,
  'url': 'https://www.google.com/maps/place/Jeemann+Restaurant/data=!4m7!3m6!1s0x39418b1011ecb3bf:0x2d9f39d7c848a769!8m2!3d26.2134608!4d73.0222376!16s%2Fg%2F11ffm38dc_!19sChIJv7PsERCLQTkRaadIyNc5ny0?authuser=0&hl=en&rclk=1',
  'phone': '07976085653',
  'rating': '4.2'},
 {'id': 3,
  'url': 'https://www.google.com/maps/place/The+Plant+Story+Restaurant/data=!4m7!3m6!1s0x39418d244effef09:0xd7a6df821524706b!8m2!3d26.2819051!4d73.0048006!16s%2Fg%2F11mw8l6vmd!19sChIJCe__TiSNQTkRa3AkFYLfptc?authuser=0&hl=en&rclk=1',
  'phone': '08989920000',
  'website': 'https://theplantstory.co.in/',
  'rating': '4.5'},
 {'id': 4,
  'url': 'https://www.google.com/maps/place/O+High+Jodhpur/data=!4m7!3m6!1s0x39418dd8427d29d3:0x86839c32bc0163ab!8m2!3d26.2499201!4d72.9788011!16s%2Fg%2F11vrzls2xp!19sChIJ0yl9QtiNQTkRq2MBvDKcg4Y?authuser=0&hl=en&rclk=1',
  'phone': '09116952516',
  'website': 'https://www.swiggy.com/restaurants/o-high-keshavnagar-koramangala-jodhpur-1336281/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.8'},
 {'id': 5,
  'url': 'https://www.google.com/maps/place/Maa+Ki+Dhani+%28%E0%A4%AE%E0%A4%BE%E0%A4%81+%E0%A4%95%E0%A5%80+%E0%A4%A2%E0%A4%BE%E0%A4%A3%E0%A5%80%29/data=!4m7!3m6!1s0x39418b6950582477:0x9893257857f791f9!8m2!3d26.2344965!4d73.0180081!16s%2Fg%2F11vx0kh6nf!19sChIJdyRYUGmLQTkR-ZH3V3glk5g?authuser=0&hl=en&rclk=1',
  'phone': '09929119295',
  'website': 'https://maakidhani.in/',
  'rating': '4.7'},
 {'id': 6,
  'url': 'https://www.google.com/maps/place/The+Grand+Turf+Pure+Vegetarian+Family+Restaurant/data=!4m7!3m6!1s0x39418b9fe0480753:0x249df01907b946aa!8m2!3d26.2207012!4d73.0414787!16s%2Fg%2F11gdy2hf1y!19sChIJUwdI4J-LQTkRqka5BxnwnSQ?authuser=0&hl=en&rclk=1',
  'phone': '09619319099',
  'website': 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x683/428978571.jpg?k\\u003d14e59b49319ebd00fb6528509fb0c06dd180f89b6f6891a41d674e719b67ff01\\u0026o\\u003d\\u0026a\\u003d1538557',
  'rating': '4.5'},
 {'id': 7,
  'url': 'https://www.google.com/maps/place/Kesar+The+Restaurant/data=!4m7!3m6!1s0x39418b448e97ac67:0x5b6529a4ddc92e58!8m2!3d26.2194202!4d73.0264175!16s%2Fg%2F11stkm3f58!19sChIJZ6yXjkSLQTkRWC7J3aQpZVs?authuser=0&hl=en&rclk=1',
  'phone': '07878142153',
  'rating': '4.5'},
 {'id': 8,
  'url': 'https://www.google.com/maps/place/The+Olive+Court/data=!4m7!3m6!1s0x39418d0baaf148c9:0x31d82d99bbb04b9e!8m2!3d26.2697989!4d73.0385446!16s%2Fg%2F11l6htfrds!19sChIJyUjxqguNQTkRnkuwu5kt2DE?authuser=0&hl=en&rclk=1',
  'phone': '08824519693',
  'website': 'https://www.swiggy.com/restaurants/the-olive-court-ratanada-koramangala-jodhpur-969473/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.7'},
 {'id': 9,
  'url': 'https://www.google.com/maps/place/1952+A+Food+Story/data=!4m7!3m6!1s0x39418d731e264fcd:0xa4a1c6ac53b09d15!8m2!3d26.2084376!4d73.0247331!16s%2Fg%2F11jsm85f_w!19sChIJzU8mHnONQTkRFZ2wU6zGoaQ?authuser=0&hl=en&rclk=1',
  'phone': '08112296803',
  'website': 'https://www.swiggy.com/restaurants/1952-a-food-story-gopal-bari-basni-jodhpur-686791/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.8'},
 {'id': 10,
  'url': 'https://www.google.com/maps/place/Indique+Restaurant+%26+Bar/data=!4m7!3m6!1s0x39418db72d475c51:0x7c10f67cc3d86d02!8m2!3d26.2963176!4d73.0239142!16s%2Fg%2F11b70g407m!19sChIJUVxHLbeNQTkRAm3Yw3z2EHw?authuser=0&hl=en&rclk=1',
  'phone': '09672293328',
  'website': 'https://www.palhaveli.com/indiquerestaurant',
  'rating': '4.3'},
 {'id': 11,
  'url': 'https://www.google.com/maps/place/THE+SPICE+STORY+II+BEST+VEGETARIAN+FAMILY+RESTAURANT+II+FINE+DINE+%26+ROOFTOP/data=!4m7!3m6!1s0x39418d1100aadcdb:0xba448337948070c8!8m2!3d26.2793265!4d73.0375348!16s%2Fg%2F11txlcncbj!19sChIJ29yqABGNQTkRyHCAlDeDRLo?authuser=0&hl=en&rclk=1',
  'phone': '09001890329',
  'website': 'https://www.swiggy.com/restaurants/the-spice-story-ratanada-basni-jodhpur-913297/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.7'},
 {'id': 12,
  'url': 'https://www.google.com/maps/place/Indigo+Restaurant/data=!4m7!3m6!1s0x39418db744033e3f:0x308e593b418fc2d5!8m2!3d26.2975992!4d73.0218181!16s%2Fg%2F11b6d4cfsd!19sChIJPz4DRLeNQTkR1cKPQTtZjjA?authuser=0&hl=en&rclk=1',
  'phone': '09829524809',
  'rating': '4.6'},
 {'id': 13,
  'url': 'https://www.google.com/maps/place/Unaavu/data=!4m7!3m6!1s0x39418d9be9e31b8d:0x820427f902583eb4!8m2!3d26.267619!4d73.0396952!16s%2Fg%2F11t7z69j65!19sChIJjRvj6ZuNQTkRtD5YAvknBII?authuser=0&hl=en&rclk=1',
  'phone': '08824867154',
  'website': 'https://www.swiggy.com/restaurants/unaavu-ratanada-new-jodhpur-jodhpur-645977/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.6'},
 {'id': 14,
  'url': 'https://www.google.com/maps/place/Spicy+Table/data=!4m7!3m6!1s0x39418ba85299866d:0x8108d03980161675!8m2!3d26.227094!4d73.0394165!16s%2Fg%2F11ww8qhtqv!19sChIJbYaZUqiLQTkRdRYWgDnQCIE?authuser=0&hl=en&rclk=1',
  'phone': '08905460304',
  'rating': '4.5'},
 {'id': 15,
  'url': 'https://www.google.com/maps/place/The+Flamingo/data=!4m7!3m6!1s0x39418def813c43e3:0xcfb5ffe749b2b3a6!8m2!3d26.2703777!4d73.0377509!16s%2Fg%2F11frlhmvts!19sChIJ40M8ge-NQTkRprOySef_tc8?authuser=0&hl=en&rclk=1',
  'phone': '07877573264',
  'website': 'https://www.swiggy.com/restaurants/the-flamingo-ratanada-new-jodhpur-jodhpur-383652/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.6'},
 {'id': 16,
  'url': 'https://www.google.com/maps/place/Bhootnath+Restaurant+%26+cafe/data=!4m7!3m6!1s0x39418d7b4637094b:0xc855848de9f0b4fd!8m2!3d26.2729449!4d73.0253689!16s%2Fg%2F11tnmb41zs!19sChIJSwk3RnuNQTkR_bTw6Y2EVcg?authuser=0&hl=en&rclk=1',
  'rating': '4.9'},
 {'id': 17,
  'url': 'https://www.google.com/maps/place/Maverick+Jodhpur/data=!4m7!3m6!1s0x39418dc20e1e0081:0xccc2caa02b7e8799!8m2!3d26.2707051!4d73.03016!16s%2Fg%2F11lyxkbmjj!19sChIJgQAeDsKNQTkRmYd-K6DKwsw?authuser=0&hl=en&rclk=1',
  'phone': '08440908000',
  'website': 'https://maverickjodhpur.com/',
  'rating': '4.6'},
 {'id': 18,
  'url': 'https://www.google.com/maps/place/VYANJANAM/data=!4m7!3m6!1s0x39418dc55b387043:0x987018859e7e92f7!8m2!3d26.2773173!4d73.004203!16s%2Fg%2F11s5c_n_6t!19sChIJQ3A4W8WNQTkR95J-noUYcJg?authuser=0&hl=en&rclk=1',
  'phone': '07240100021',
  'rating': '4.7'},
 {'id': 19,
  'url': 'https://www.google.com/maps/place/Kalinga+Restaurant/data=!4m7!3m6!1s0x39418c4b715e48d3:0xb8b9f9b29db318ab!8m2!3d26.2844136!4d73.0215372!16s%2Fg%2F11b6zpcd3l!19sChIJ00hecUuMQTkRqxiznbL5ubg?authuser=0&hl=en&rclk=1',
  'phone': '07300054888',
  'website': 'https://www.swiggy.com/restaurants/kalinga-restaurant-ratanada-new-jodhpur-jodhpur-85757/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.2'},
 {'id': 20,
  'url': 'https://www.google.com/maps/place/On+The+Rocks/data=!4m7!3m6!1s0x39418c565fb9169d:0x4d9b71f195878ac!8m2!3d26.2817423!4d73.0376391!16s%2Fg%2F1td9c4h_!19sChIJnRa5X1aMQTkRrHhYGR-32QQ?authuser=0&hl=en&rclk=1',
  'phone': '09119364555',
  'rating': '4.2'},
 {'id': 21,
  'url': 'https://www.google.com/maps/place/Gopal+Roof+Top+Restaurant+%28+Rajsthani+Cuisine+%26+Lal+Maas+%29/data=!4m7!3m6!1s0x39418db72e828651:0xc56036a9188ddc0c!8m2!3d26.2964128!4d73.0222544!16s%2Fg%2F11h4s21zy4!19sChIJUYaCLreNQTkRDNyNGKk2YMU?authuser=0&hl=en&rclk=1',
  'phone': '09828230781',
  'website': 'https://link.zomato.com/xqzv/rshare?id\\u003d19923423bdcb9b36',
  'rating': '4.6'},
 {'id': 22,
  'url': 'https://www.google.com/maps/place/Jodhpur+Veg,+Non-Veg+%26+Fast+Food+Restaurant/data=!4m7!3m6!1s0x39418b772916c10b:0x4386c1efccbc07aa!8m2!3d26.2090485!4d73.0272835!16s%2Fg%2F11g30_q28t!19sChIJC8EWKXeLQTkRqge8zO_BhkM?authuser=0&hl=en&rclk=1',
  'phone': '08239640772',
  'rating': '3.9'},
 {'id': 23,
  'url': 'https://www.google.com/maps/place/Acharya+Rooftop+Restaurant+%26+Guest+House/data=!4m7!3m6!1s0x39418d637748c325:0x9da135c45a7add13!8m2!3d26.2981184!4d73.0211105!16s%2Fg%2F11tnnqbfq_!19sChIJJcNId2ONQTkRE916WsQ1oZ0?authuser=0&hl=en&rclk=1',
  'phone': '09024077490',
  'rating': '4.8'},
 {'id': 24,
  'url': 'https://www.google.com/maps/place/Divyanshi+The+Taste+Of+Jodhpur+Veg-Non+Veg+Restaurant/data=!4m7!3m6!1s0x39418bcc3355a1a5:0xb6503b3beb38376d!8m2!3d26.2160158!4d73.0153581!16s%2Fg%2F11l5vh0cc_!19sChIJpaFVM8yLQTkRbTc46zs7ULY?authuser=0&hl=en&rclk=1',
  'phone': '09636533777',
  'website': 'https://www.swiggy.com/restaurants/the-taste-of-jodhpur-meera-nagar-basni-jodhpur-799435/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.5'},
 {'id': 25,
  'url': 'https://www.google.com/maps/place/Gypsy+Vegetarian+Restaurant/data=!4m7!3m6!1s0x39418d2be40d9b47:0xc82a0250d43fbf36!8m2!3d26.2751618!4d73.0077764!16s%2Fg%2F1td74zyg!19sChIJR5sN5CuNQTkRNr8_1FACKsg?authuser=0&hl=en&rclk=1',
  'phone': '07412074075',
  'rating': '4'},
 {'id': 26,
  'url': 'https://www.google.com/maps/place/Kasturi+Flavours+Restaurant+-+Jodhpur/data=!4m7!3m6!1s0x39418938220cc6d3:0x8e9dd95f27abadad!8m2!3d26.2223226!4d72.9686233!16s%2Fg%2F11fzfbswy8!19sChIJ08YMIjiJQTkRra2rJ1_ZnY4?authuser=0&hl=en&rclk=1',
  'phone': '08094008357',
  'website': 'https://www.kasturiorchid.com/our-restaurant/',
  'rating': '4.7'},
 {'id': 27,
  'url': 'https://www.google.com/maps/place/Kava+Restaurant+And+Lounge+-+Fairfield+by+Marriott+Jodhpur/data=!4m7!3m6!1s0x39418ba8c4821ee5:0xd26c660eb4d42929!8m2!3d26.2172753!4d73.0448635!16s%2Fg%2F11hgp1lrg5!19sChIJ5R6CxKiLQTkRKSnUtA5mbNI?authuser=0&hl=en&rclk=1',
  'phone': '02917112222',
  'website': 'https://www.marriott.com/hotels/hotel-information/restaurant/jdhfi-fairfield-jodhpur/',
  'rating': '4.1'},
 {'id': 28,
  'url': 'https://www.google.com/maps/place/ON+THE+FARM+%28OTF%29/data=!4m7!3m6!1s0x39418df1046db9e3:0xa9ec373a9c91c269!8m2!3d26.2644886!4d73.0593399!16s%2Fg%2F11qh2wqsr1!19sChIJ47ltBPGNQTkRacKRnDo37Kk?authuser=0&hl=en&rclk=1',
  'phone': '07014295011',
  'rating': '4.2'},
 {'id': 29,
  'url': 'https://www.google.com/maps/place/Rigveda%E2%80%99+Jodhpur/data=!4m7!3m6!1s0x39418c46dea1c0cd:0x7d5412512b88e751!8m2!3d26.2708648!4d73.0201595!16s%2Fg%2F11cnb89xpl!19sChIJzcCh3kaMQTkRUeeIK1ESVH0?authuser=0&hl=en&rclk=1',
  'phone': '09314784000',
  'website': 'https://www.swiggy.com/restaurants/rigveda-ratanada-basni-jodhpur-866880/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.4'},
 {'id': 30,
  'url': 'https://www.google.com/maps/place/Hari+Vedas%27+Jodhpur/data=!4m7!3m6!1s0x39418c307664eaf9:0x2c7c6b5a19c2c869!8m2!3d26.2741545!4d73.0070067!16s%2Fg%2F11b67f3frf!19sChIJ-epkdjCMQTkRacjCGVprfCw?authuser=0&hl=en&rclk=1',
  'phone': '02912444444',
  'website': 'https://www.swiggy.com/restaurants/hari-vedas-sardarpura-basni-jodhpur-866802/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.2'},
 {'id': 31,
  'url': 'https://www.google.com/maps/place/Vegetrainian+-+The+Train+Restaurant/data=!4m7!3m6!1s0x39418d472a9ddfdb:0xc94c978068428e5e!8m2!3d26.2665463!4d73.0235491!16s%2Fg%2F11h4pcb9cq!19sChIJ29-dKkeNQTkRXo5CaICXTMk?authuser=0&hl=en&rclk=1',
  'phone': '08905005600',
  'website': 'https://www.swiggy.com/restaurants/vegetrainian-the-train-restaurant-sardarpura-new-jodhpur-jodhpur-513288/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.3'},
 {'id': 32,
  'url': 'https://www.google.com/maps/place/Ricotta/data=!4m7!3m6!1s0x39418d0538500a97:0xc7ce032f95befc7e!8m2!3d26.2713891!4d73.0081135!16s%2Fg%2F11krhm6t16!19sChIJlwpQOAWNQTkRfvy-lS8Dzsc?authuser=0&hl=en&rclk=1',
  'phone': '09352197529',
  'website': 'https://www.swiggy.com/restaurants/ricotta-shastri-nagar-koramangala-jodhpur-1055698/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.7'},
 {'id': 33,
  'url': 'https://www.google.com/maps/place/Shree+Subhadra+hotel+$+family+restaurant/data=!4m7!3m6!1s0x39418bbcac3497df:0x3e7ea7eadf40c821!8m2!3d26.2138014!4d73.0285518!16s%2Fg%2F1hm22vqtd!19sChIJ35c0rLyLQTkRIchA3-qnfj4?authuser=0&hl=en&rclk=1',
  'phone': '09829611960',
  'rating': '4.1'},
 {'id': 34,
  'url': 'https://www.google.com/maps/place/SAGA/data=!4m7!3m6!1s0x39418db7167277d9:0x599558aa5c4460d4!8m2!3d26.2708205!4d73.0302959!16s%2Fg%2F11h80dw6sx!19sChIJ2XdyFreNQTkR1GBEXKpYlVk?authuser=0&hl=en&rclk=1',
  'phone': '08824688830',
  'website': 'https://www.swiggy.com/restaurants/saga-ratanada-new-jodhpur-jodhpur-548990/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.6'},
 {'id': 35,
  'url': 'https://www.google.com/maps/place/Bungalow+12/data=!4m7!3m6!1s0x39418dde1e2a49d7:0x3b1c3e7d5b012df4!8m2!3d26.2675243!4d73.0309974!16s%2Fg%2F11nxqyxdrl!19sChIJ10kqHt6NQTkR9C0BW30-HDs?authuser=0&hl=en&rclk=1',
  'phone': '09828561212',
  'website': 'https://www.instagram.com/bungalow.twelve/',
  'rating': '4.4'},
 {'id': 36,
  'url': 'https://www.google.com/maps/place/The+Big+%22O%22+Restaurant+and+Lounge/data=!4m7!3m6!1s0x39418fe00fab856b:0x6ba5c8f3c44d6a76!8m2!3d26.2449574!4d72.9737318!16s%2Fg%2F11fsk9k4wq!19sChIJa4WrD-CPQTkRdmpNxPPIpWs?authuser=0&hl=en&rclk=1',
  'phone': '07568502020',
  'website': 'https://www.swiggy.com/restaurants/the-big-o-restaurant-and-lounge-near-hp-petrol-pump-west-jodhpur-jodhpur-686551/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.1'},
 {'id': 37,
  'url': 'https://www.google.com/maps/place/Haldi+Restaurant+%26+Banquet+Hall/data=!4m7!3m6!1s0x39418b7e0e0353e7:0xfe37b017b732c148!8m2!3d26.2370208!4d73.0100165!16s%2Fg%2F11sfbtw6r_!19sChIJ51MDDn6LQTkRSMEytxewN_4?authuser=0&hl=en&rclk=1',
  'phone': '08769238369',
  'website': 'https://www.zomato.com/jodhpur/haldi-restaurant-basni',
  'rating': '4.4'},
 {'id': 38,
  'url': 'https://www.google.com/maps/place/Gazania+Restaurant/data=!4m7!3m6!1s0x39418d4ca1581d11:0x6731e7c01fbb87d2!8m2!3d26.2765089!4d73.0347203!16s%2Fg%2F11tdnk47gr!19sChIJER1YoUyNQTkR0oe7H8DnMWc?authuser=0&hl=en&rclk=1',
  'phone': '07300009192',
  'rating': '4.1'},
 {'id': 39,
  'url': 'https://www.google.com/maps/place/Pet+Pooja+Veg+%26+Non-veg+restaurant/data=!4m7!3m6!1s0x39418b1bff20e36b:0x5ec827d0c561c0fd!8m2!3d26.2082163!4d73.025086!16s%2Fg%2F11rqxsf50r!19sChIJa-Mg_xuLQTkR_cBhxdAnyF4?authuser=0&hl=en&rclk=1',
  'phone': '08003802957',
  'rating': '5'},
 {'id': 40,
  'url': 'https://www.google.com/maps/place/ZEEMLOGY+RESTAURANT/data=!4m7!3m6!1s0x39418d5e9c83aed1:0x7e21007009709f1a!8m2!3d26.2771007!4d73.0328628!16s%2Fg%2F11vdzvw6wc!19sChIJ0a6DnF6NQTkRGp9wCXAAIX4?authuser=0&hl=en&rclk=1',
  'phone': '09929672219',
  'website': 'https://www.swiggy.com/restaurants/zeemlogy-restaurant-ratanada-koramangala-jodhpur-1129095/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.6'},
 {'id': 41,
  'url': 'https://www.google.com/maps/place/DARBAARI+-+THE+INDIAN+GRILLS+II+BEST+NON+VEGETARIAN+RESTAURANT/data=!4m7!3m6!1s0x39418d000b0aec39:0xab8829ee69838410!8m2!3d26.2710068!4d73.0387964!16s%2Fg%2F11wg4zhwnt!19sChIJOewKCwCNQTkREISDae4piKs?authuser=0&hl=en&rclk=1',
  'website': 'https://www.zomato.com/jodhpur/darbaari-the-indian-grills-1-ratanada/book?utm_source\\u003drwg',
  'rating': '4.5'},
 {'id': 42,
  'url': 'https://www.google.com/maps/place/THE+SOLO+HOUSE+RESTAURANT/data=!4m7!3m6!1s0x39418d001fdaf791:0x2fb039ccff4d1f7e!8m2!3d26.2712082!4d73.0291063!16s%2Fg%2F11m64vsc28!19sChIJkffaHwCNQTkRfh9N_8w5sC8?authuser=0&hl=en&rclk=1',
  'phone': '08358005900',
  'website': 'https://thesolohouseindia.com/',
  'rating': '4.8'},
 {'id': 43,
  'url': 'https://www.google.com/maps/place/Shree+Balaji+Restaurant/data=!4m7!3m6!1s0x39418b0652df413f:0x220d9c6dce23d1b7!8m2!3d26.205699!4d73.0151944!16s%2Fg%2F11k9jcxk6g!19sChIJP0HfUgaLQTkRt9Ejzm2cDSI?authuser=0&hl=en&rclk=1',
  'phone': '08290739066',
  'rating': '4.7'},
 {'id': 44,
  'url': 'https://www.google.com/maps/place/Barbeque+On+Table/data=!4m7!3m6!1s0x39418ba59bde33bf:0x68dbfdc289912f62!8m2!3d26.2704395!4d73.0401234!16s%2Fg%2F11t2z0f4vg!19sChIJvzPem6WLQTkRYi-RicL922g?authuser=0&hl=en&rclk=1',
  'phone': '09521677773',
  'website': 'https://www.swiggy.com/restaurants/barbeque-on-table-defence-lab-road-new-jodhpur-jodhpur-708012/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.3'},
 {'id': 45,
  'url': 'https://www.google.com/maps/place/Baari+restaurant/data=!4m7!3m6!1s0x39418da60e04df95:0xbe0cbc41916e80b4!8m2!3d26.3011601!4d73.0353292!16s%2Fg%2F11c31pn5_h!19sChIJld8EDqaNQTkRtIBukUG8DL4?authuser=0&hl=en&rclk=1',
  'phone': '09660059488',
  'website': 'https://www.swiggy.com/restaurants/baari-restaurant-and-lounge-paota-koramangala-jodhpur-1070904/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.6'},
 {'id': 46,
  'url': 'https://www.google.com/maps/place/The+1932+House/data=!4m7!3m6!1s0x39418d611b593045:0xbedda3b93ab26686!8m2!3d26.274926!4d73.0245367!16s%2Fg%2F11w221lyc_!19sChIJRTBZG2GNQTkRhmayOrmj3b4?authuser=0&hl=en&rclk=1',
  'phone': '08769711851',
  'website': 'https://www.swiggy.com/restaurants/the-1932-house-ratanada-koramangala-jodhpur-977431/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.7'},
 {'id': 47,
  'url': 'https://www.google.com/maps/place/The+Recipe+Restaurant/data=!4m7!3m6!1s0x39418c3a4e37cd57:0xfd154ac6cd9077ed!8m2!3d26.2718828!4d73.0088614!16s%2Fg%2F11b6j7yrvn!19sChIJV803TjqMQTkR7XeQzcZKFf0?authuser=0&hl=en&rclk=1',
  'phone': '09928371291',
  'website': 'https://www.swiggy.com/restaurants/the-recipe-restaurant-sardarpura-old-jodhpur-jodhpur-1366959/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve',
  'rating': '4.1'},
 {'id': 48,
  'url': 'https://www.google.com/maps/place/The+busy+beans+cafe+%26+Restaurant/data=!4m7!3m6!1s0x39418b6a20331925:0x6c6758bd33391dd8!8m2!3d26.2150736!4d73.025664!16s%2Fg%2F11tj2hgk8g!19sChIJJRkzIGqLQTkR2B05M71YZ2w?authuser=0&hl=en&rclk=1',
  'phone': '08432876262',
  'rating': '4.6'},
 {'id': 49,
  'url': 'https://www.google.com/maps/place/Anna+Cafe+And+Restaurant%E2%80%8D+Jodhpur/data=!4m7!3m6!1s0x39418d7389cdb5a7:0x791e6fccaaf2b963!8m2!3d26.3017612!4d73.0231656!16s%2Fg%2F11vl8t4j1z!19sChIJp7XNiXONQTkRY7nyqsxvHnk?authuser=0&hl=en&rclk=1',
  'phone': '09414391265',
  'rating': '4.9'},
 {'id': 50,

In [46]:
import pandas as pd

res_df = pd.DataFrame(res)

In [47]:
res_df

,id,url,phone,rating,website
0,1,https://www.google.com/maps/place/House+of+Arc...,09414100102,4.8,NaN
1,2,https://www.google.com/maps/place/Jeemann+Rest...,07976085653,4.2,NaN
2,3,https://www.google.com/maps/place/The+Plant+St...,08989920000,4.5,https://theplantstory.co.in/
3,4,https://www.google.com/maps/place/O+High+Jodhp...,09116952516,4.8,https://www.swiggy.com/restaurants/o-high-kesh...
4,5,https://www.google.com/maps/place/Maa+Ki+Dhani...,09929119295,4.7,https://maakidhani.in/
...,...,...,...,...,...
194,195,https://www.google.com/maps/place/Shree+Jagdam...,NaN,3,NaN
195,196,https://www.google.com/maps/place/Hotel+Rajwar...,02912515242,4.3,https://q-xx.bstatic.com/xdata/images/hotel/ma...
196,197,https://www.google.com/maps/place/Hotel+Shri+R...,02912614101,4.2,https://freecancellationscdn-hsbgcwfragasdpfe....
197,198,https://www.google.com/maps/place/ELEVE/data=!...,NaN,3.7,https://www.swiggy.com/restaurants/eleve-novot...
198,199,https://www.google.com/maps/place/THE+CIGAR+LO...,09571192888,3.7,https://www.instagram.com/rosbyfernjodhpur?igs...

In [48]:
final_df = pd.merge(new_data,res_df,on="id",how="inner")

In [49]:
final_df

,id,Title,url_x,url_x,url_x,url_x,url_y,phone,rating,website
0,1,House of Arches,https://www.google.com/maps/place/House+of+Arc...,https://www.google.com/maps/place/House+of+Arc...,https://www.google.com/maps/place/House+of+Arc...,https://www.google.com/maps/place/House+of+Arc...,https://www.google.com/maps/place/House+of+Arc...,09414100102,4.8,NaN
1,2,Jeemann Restaurant,https://www.google.com/maps/place/Jeemann+Rest...,https://www.google.com/maps/place/Jeemann+Rest...,https://www.google.com/maps/place/Jeemann+Rest...,https://www.google.com/maps/place/Jeemann+Rest...,https://www.google.com/maps/place/Jeemann+Rest...,07976085653,4.2,NaN
2,3,The Plant Story Restaurant,https://www.google.com/maps/place/The+Plant+St...,https://www.google.com/maps/place/The+Plant+St...,https://www.google.com/maps/place/The+Plant+St...,https://www.google.com/maps/place/The+Plant+St...,https://www.google.com/maps/place/The+Plant+St...,08989920000,4.5,https://theplantstory.co.in/
3,4,O High Jodhpur,https://www.google.com/maps/place/O+High+Jodhp...,https://www.google.com/maps/place/O+High+Jodhp...,https://www.google.com/maps/place/O+High+Jodhp...,https://www.google.com/maps/place/O+High+Jodhp...,https://www.google.com/maps/place/O+High+Jodhp...,09116952516,4.8,https://www.swiggy.com/restaurants/o-high-kesh...
4,5,Maa Ki Dhani (माँ की ढाणी),https://www.google.com/maps/place/Maa+Ki+Dhani...,https://www.google.com/maps/place/Maa+Ki+Dhani...,https://www.google.com/maps/place/Maa+Ki+Dhani...,https://www.google.com/maps/place/Maa+Ki+Dhani...,https://www.google.com/maps/place/Maa+Ki+Dhani...,09929119295,4.7,https://maakidhani.in/
...,...,...,...,...,...,...,...,...,...,...
194,195,Shree Jagdamba Wine Shop,https://www.google.com/maps/place/Shree+Jagdam...,https://www.google.com/maps/place/Shree+Jagdam...,https://www.google.com/maps/place/Shree+Jagdam...,https://www.google.com/maps/place/Shree+Jagdam...,https://www.google.com/maps/place/Shree+Jagdam...,NaN,3,NaN
195,196,Hotel Rajwara Palace Jodhpur,https://www.google.com/maps/place/Hotel+Rajwar...,https://www.google.com/maps/place/Hotel+Rajwar...,https://www.google.com/maps/place/Hotel+Rajwar...,https://www.google.com/maps/place/Hotel+Rajwar...,https://www.google.com/maps/place/Hotel+Rajwar...,02912515242,4.3,https://q-xx.bstatic.com/xdata/images/hotel/ma...
196,197,"₹1,534",https://www.google.com/maps/place/Hotel+Shri+R...,https://www.google.com/maps/place/Hotel+Shri+R...,https://www.google.com/maps/place/Hotel+Shri+R...,https://www.google.com/maps/place/Hotel+Shri+R...,https://www.google.com/maps/place/Hotel+Shri+R...,02912614101,4.2,https://freecancellationscdn-hsbgcwfragasdpfe....
197,198,Hotel Shri Ram Excellency - Banquet Hall in Jo...,https://www.google.com/maps/place/ELEVE/data=!...,https://www.google.com/maps/place/ELEVE/data=!...,https://www.google.com/maps/place/ELEVE/data=!...,https://www.google.com/maps/place/ELEVE/data=!...,https://www.google.com/maps/place/ELEVE/data=!...,NaN,3.7,https://www.swiggy.com/restaurants/eleve-novot...
198,199,"₹2,405",https://www.google.com/maps/place/THE+CIGAR+LO...,https://www.google.com/maps/place/THE+CIGAR+LO...,https://www.google.com/maps/place/THE+CIGAR+LO...,https://www.google.com/maps/place/THE+CIGAR+LO...,https://www.google.com/maps/place/THE+CIGAR+LO...,09571192888,3.7,https://www.instagram.com/rosbyfernjodhpur?igs...

In [71]:
final_df.rename(columns={"Title" : "name","url_y": "url"},inplace=True)
final_df

,id,name,url,phone,rating,website
0,1,House of Arches,https://www.google.com/maps/place/House+of+Arc...,09414100102,4.8,NaN
1,2,Jeemann Restaurant,https://www.google.com/maps/place/Jeemann+Rest...,07976085653,4.2,NaN
2,3,The Plant Story Restaurant,https://www.google.com/maps/place/The+Plant+St...,08989920000,4.5,https://theplantstory.co.in/
3,4,O High Jodhpur,https://www.google.com/maps/place/O+High+Jodhp...,09116952516,4.8,https://www.swiggy.com/restaurants/o-high-kesh...
4,5,Maa Ki Dhani (माँ की ढाणी),https://www.google.com/maps/place/Maa+Ki+Dhani...,09929119295,4.7,https://maakidhani.in/
...,...,...,...,...,...,...
194,195,Shree Jagdamba Wine Shop,https://www.google.com/maps/place/Shree+Jagdam...,NaN,3,NaN
195,196,Hotel Rajwara Palace Jodhpur,https://www.google.com/maps/place/Hotel+Rajwar...,02912515242,4.3,https://q-xx.bstatic.com/xdata/images/hotel/ma...
196,197,"₹1,534",https://www.google.com/maps/place/Hotel+Shri+R...,02912614101,4.2,https://freecancellationscdn-hsbgcwfragasdpfe....
197,198,Hotel Shri Ram Excellency - Banquet Hall in Jo...,https://www.google.com/maps/place/ELEVE/data=!...,NaN,3.7,https://www.swiggy.com/restaurants/eleve-novot...
198,199,"₹2,405",https://www.google.com/maps/place/THE+CIGAR+LO...,09571192888,3.7,https://www.instagram.com/rosbyfernjodhpur?igs...

In [50]:
final_df = final_df.drop(columns=["url_x"])

In [81]:
final_df

,id,name,url,phone,rating,website
0,1,House of Arches,https://www.google.com/maps/place/House+of+Arc...,09414100102,4.8,NaN
1,2,Jeemann Restaurant,https://www.google.com/maps/place/Jeemann+Rest...,07976085653,4.2,NaN
2,3,The Plant Story Restaurant,https://www.google.com/maps/place/The+Plant+St...,08989920000,4.5,https://theplantstory.co.in/
3,4,O High Jodhpur,https://www.google.com/maps/place/O+High+Jodhp...,09116952516,4.8,https://www.swiggy.com/restaurants/o-high-kesh...
4,5,Maa Ki Dhani (माँ की ढाणी),https://www.google.com/maps/place/Maa+Ki+Dhani...,09929119295,4.7,https://maakidhani.in/
...,...,...,...,...,...,...
194,195,Shree Jagdamba Wine Shop,https://www.google.com/maps/place/Shree+Jagdam...,NaN,3,NaN
195,196,Hotel Rajwara Palace Jodhpur,https://www.google.com/maps/place/Hotel+Rajwar...,02912515242,4.3,https://q-xx.bstatic.com/xdata/images/hotel/ma...
196,197,"₹1,534",https://www.google.com/maps/place/Hotel+Shri+R...,02912614101,4.2,https://freecancellationscdn-hsbgcwfragasdpfe....
197,198,Hotel Shri Ram Excellency - Banquet Hall in Jo...,https://www.google.com/maps/place/ELEVE/data=!...,NaN,3.7,https://www.swiggy.com/restaurants/eleve-novot...
198,199,"₹2,405",https://www.google.com/maps/place/THE+CIGAR+LO...,09571192888,3.7,https://www.instagram.com/rosbyfernjodhpur?igs...

In [77]:
import data_in_excle_finished as dif
import importlib
importlib.reload(dif)

In [82]:
final_df.columns

Index(['id', 'name', 'url', 'phone', 'rating', 'website'], dtype='str')

In [83]:
dif.crete_lead_excel_file(final_df.to_dict(orient="records"))

{'id': 1, 'name': 'House of Arches', 'url': 'https://www.google.com/maps/place/House+of+Arches/data=!4m7!3m6!1s0x394189ff6d264b6b:0xa707a9092556bcfd!8m2!3d26.2189887!4d72.9791311!16s%2Fg%2F11vbv0cjcs!19sChIJa0smbf-JQTkR_bxWJQmpB6c?authuser=0&hl=en&rclk=1', 'phone': '09414100102', 'rating': '4.8', 'website': nan}
{'id': 2, 'name': 'Jeemann Restaurant', 'url': 'https://www.google.com/maps/place/Jeemann+Restaurant/data=!4m7!3m6!1s0x39418b1011ecb3bf:0x2d9f39d7c848a769!8m2!3d26.2134608!4d73.0222376!16s%2Fg%2F11ffm38dc_!19sChIJv7PsERCLQTkRaadIyNc5ny0?authuser=0&hl=en&rclk=1', 'phone': '07976085653', 'rating': '4.2', 'website': nan}
{'id': 3, 'name': 'The Plant Story Restaurant', 'url': 'https://www.google.com/maps/place/The+Plant+Story+Restaurant/data=!4m7!3m6!1s0x39418d244effef09:0xd7a6df821524706b!8m2!3d26.2819051!4d73.0048006!16s%2Fg%2F11mw8l6vmd!19sChIJCe__TiSNQTkRa3AkFYLfptc?authuser=0&hl=en&rclk=1', 'phone': '08989920000', 'rating': '4.5', 'website': 'https://theplantstory.co.in/'}
{'id': 4, 'name': 'O High Jodhpur', 'url': 'https://www.google.com/maps/place/O+High+Jodhpur/data=!4m7!3m6!1s0x39418dd8427d29d3:0x86839c32bc0163ab!8m2!3d26.2499201!4d72.9788011!16s%2Fg%2F11vrzls2xp!19sChIJ0yl9QtiNQTkRq2MBvDKcg4Y?authuser=0&hl=en&rclk=1', 'phone': '09116952516', 'rating': '4.8', 'website': 'https://www.swiggy.com/restaurants/o-high-keshavnagar-koramangala-jodhpur-1336281/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 5, 'name': 'Maa Ki Dhani (माँ की ढाणी)', 'url': 'https://www.google.com/maps/place/Maa+Ki+Dhani+%28%E0%A4%AE%E0%A4%BE%E0%A4%81+%E0%A4%95%E0%A5%80+%E0%A4%A2%E0%A4%BE%E0%A4%A3%E0%A5%80%29/data=!4m7!3m6!1s0x39418b6950582477:0x9893257857f791f9!8m2!3d26.2344965!4d73.0180081!16s%2Fg%2F11vx0kh6nf!19sChIJdyRYUGmLQTkR-ZH3V3glk5g?authuser=0&hl=en&rclk=1', 'phone': '09929119295', 'rating': '4.7', 'website': 'https://maakidhani.in/'}
{'id': 6, 'name': 'The Grand Turf Pure Vegetarian Family Restaurant', 'url': 'https://www.google.com/maps/place/The+Grand+Turf+Pure+Vegetarian+Family+Restaurant/data=!4m7!3m6!1s0x39418b9fe0480753:0x249df01907b946aa!8m2!3d26.2207012!4d73.0414787!16s%2Fg%2F11gdy2hf1y!19sChIJUwdI4J-LQTkRqka5BxnwnSQ?authuser=0&hl=en&rclk=1', 'phone': '09619319099', 'rating': '4.5', 'website': 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x683/428978571.jpg?k\\u003d14e59b49319ebd00fb6528509fb0c06dd180f89b6f6891a41d674e719b67ff01\\u0026o\\u003d\\u0026a\\u003d1538557'}
{'id': 7, 'name': 'Kesar The Restaurant', 'url': 'https://www.google.com/maps/place/Kesar+The+Restaurant/data=!4m7!3m6!1s0x39418b448e97ac67:0x5b6529a4ddc92e58!8m2!3d26.2194202!4d73.0264175!16s%2Fg%2F11stkm3f58!19sChIJZ6yXjkSLQTkRWC7J3aQpZVs?authuser=0&hl=en&rclk=1', 'phone': '07878142153', 'rating': '4.5', 'website': nan}
{'id': 8, 'name': 'The Olive Court', 'url': 'https://www.google.com/maps/place/The+Olive+Court/data=!4m7!3m6!1s0x39418d0baaf148c9:0x31d82d99bbb04b9e!8m2!3d26.2697989!4d73.0385446!16s%2Fg%2F11l6htfrds!19sChIJyUjxqguNQTkRnkuwu5kt2DE?authuser=0&hl=en&rclk=1', 'phone': '08824519693', 'rating': '4.7', 'website': 'https://www.swiggy.com/restaurants/the-olive-court-ratanada-koramangala-jodhpur-969473/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 9, 'name': '1952 A Food Story', 'url': 'https://www.google.com/maps/place/1952+A+Food+Story/data=!4m7!3m6!1s0x39418d731e264fcd:0xa4a1c6ac53b09d15!8m2!3d26.2084376!4d73.0247331!16s%2Fg%2F11jsm85f_w!19sChIJzU8mHnONQTkRFZ2wU6zGoaQ?authuser=0&hl=en&rclk=1', 'phone': '08112296803', 'rating': '4.8', 'website': 'https://www.swiggy.com/restaurants/1952-a-food-story-gopal-bari-basni-jodhpur-686791/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 10, 'name': 'Indique Restaurant & Bar', 'url': 'https://www.google.com/maps/place/Indique+Restaurant+%26+Bar/data=!4m7!3m6!1s0x39418db72d475c51:0x7c10f67cc3d86d02!8m2!3d26.2963176!4d73.0239142!16s%2Fg%2F11b70g407m!19sChIJUVxHLbeNQTkRAm3Yw3z2EHw?authuser=0&hl=en&rclk=1', 'phone': '09672293328', 'rating': '4.3', 'website': 'https://www.palhaveli.com/indiquerestaurant'}
{'id': 11, 'name': 'THE SPICE STORY II BEST VEGETARIAN FAMILY RESTAURANT II FINE DINE & ROOFTOP', 'url': 'https://www.google.com/maps/place/THE+SPICE+STORY+II+BEST+VEGETARIAN+FAMILY+RESTAURANT+II+FINE+DINE+%26+ROOFTOP/data=!4m7!3m6!1s0x39418d1100aadcdb:0xba448337948070c8!8m2!3d26.2793265!4d73.0375348!16s%2Fg%2F11txlcncbj!19sChIJ29yqABGNQTkRyHCAlDeDRLo?authuser=0&hl=en&rclk=1', 'phone': '09001890329', 'rating': '4.7', 'website': 'https://www.swiggy.com/restaurants/the-spice-story-ratanada-basni-jodhpur-913297/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 12, 'name': 'Indigo Restaurant', 'url': 'https://www.google.com/maps/place/Indigo+Restaurant/data=!4m7!3m6!1s0x39418db744033e3f:0x308e593b418fc2d5!8m2!3d26.2975992!4d73.0218181!16s%2Fg%2F11b6d4cfsd!19sChIJPz4DRLeNQTkR1cKPQTtZjjA?authuser=0&hl=en&rclk=1', 'phone': '09829524809', 'rating': '4.6', 'website': nan}
{'id': 13, 'name': 'Unaavu', 'url': 'https://www.google.com/maps/place/Unaavu/data=!4m7!3m6!1s0x39418d9be9e31b8d:0x820427f902583eb4!8m2!3d26.267619!4d73.0396952!16s%2Fg%2F11t7z69j65!19sChIJjRvj6ZuNQTkRtD5YAvknBII?authuser=0&hl=en&rclk=1', 'phone': '08824867154', 'rating': '4.6', 'website': 'https://www.swiggy.com/restaurants/unaavu-ratanada-new-jodhpur-jodhpur-645977/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 14, 'name': 'Spicy Table', 'url': 'https://www.google.com/maps/place/Spicy+Table/data=!4m7!3m6!1s0x39418ba85299866d:0x8108d03980161675!8m2!3d26.227094!4d73.0394165!16s%2Fg%2F11ww8qhtqv!19sChIJbYaZUqiLQTkRdRYWgDnQCIE?authuser=0&hl=en&rclk=1', 'phone': '08905460304', 'rating': '4.5', 'website': nan}
{'id': 15, 'name': 'The Flamingo', 'url': 'https://www.google.com/maps/place/The+Flamingo/data=!4m7!3m6!1s0x39418def813c43e3:0xcfb5ffe749b2b3a6!8m2!3d26.2703777!4d73.0377509!16s%2Fg%2F11frlhmvts!19sChIJ40M8ge-NQTkRprOySef_tc8?authuser=0&hl=en&rclk=1', 'phone': '07877573264', 'rating': '4.6', 'website': 'https://www.swiggy.com/restaurants/the-flamingo-ratanada-new-jodhpur-jodhpur-383652/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 16, 'name': 'Bhootnath Restaurant & cafe', 'url': 'https://www.google.com/maps/place/Bhootnath+Restaurant+%26+cafe/data=!4m7!3m6!1s0x39418d7b4637094b:0xc855848de9f0b4fd!8m2!3d26.2729449!4d73.0253689!16s%2Fg%2F11tnmb41zs!19sChIJSwk3RnuNQTkR_bTw6Y2EVcg?authuser=0&hl=en&rclk=1', 'phone': nan, 'rating': '4.9', 'website': nan}
{'id': 17, 'name': 'Maverick Jodhpur', 'url': 'https://www.google.com/maps/place/Maverick+Jodhpur/data=!4m7!3m6!1s0x39418dc20e1e0081:0xccc2caa02b7e8799!8m2!3d26.2707051!4d73.03016!16s%2Fg%2F11lyxkbmjj!19sChIJgQAeDsKNQTkRmYd-K6DKwsw?authuser=0&hl=en&rclk=1', 'phone': '08440908000', 'rating': '4.6', 'website': 'https://maverickjodhpur.com/'}
{'id': 18, 'name': 'VYANJANAM', 'url': 'https://www.google.com/maps/place/VYANJANAM/data=!4m7!3m6!1s0x39418dc55b387043:0x987018859e7e92f7!8m2!3d26.2773173!4d73.004203!16s%2Fg%2F11s5c_n_6t!19sChIJQ3A4W8WNQTkR95J-noUYcJg?authuser=0&hl=en&rclk=1', 'phone': '07240100021', 'rating': '4.7', 'website': nan}
{'id': 19, 'name': 'Kalinga Restaurant', 'url': 'https://www.google.com/maps/place/Kalinga+Restaurant/data=!4m7!3m6!1s0x39418c4b715e48d3:0xb8b9f9b29db318ab!8m2!3d26.2844136!4d73.0215372!16s%2Fg%2F11b6zpcd3l!19sChIJ00hecUuMQTkRqxiznbL5ubg?authuser=0&hl=en&rclk=1', 'phone': '07300054888', 'rating': '4.2', 'website': 'https://www.swiggy.com/restaurants/kalinga-restaurant-ratanada-new-jodhpur-jodhpur-85757/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 20, 'name': 'On The Rocks', 'url': 'https://www.google.com/maps/place/On+The+Rocks/data=!4m7!3m6!1s0x39418c565fb9169d:0x4d9b71f195878ac!8m2!3d26.2817423!4d73.0376391!16s%2Fg%2F1td9c4h_!19sChIJnRa5X1aMQTkRrHhYGR-32QQ?authuser=0&hl=en&rclk=1', 'phone': '09119364555', 'rating': '4.2', 'website': nan}
{'id': 21, 'name': 'Gopal Roof Top Restaurant ( Rajsthani Cuisine & Lal Maas )', 'url': 'https://www.google.com/maps/place/Gopal+Roof+Top+Restaurant+%28+Rajsthani+Cuisine+%26+Lal+Maas+%29/data=!4m7!3m6!1s0x39418db72e828651:0xc56036a9188ddc0c!8m2!3d26.2964128!4d73.0222544!16s%2Fg%2F11h4s21zy4!19sChIJUYaCLreNQTkRDNyNGKk2YMU?authuser=0&hl=en&rclk=1', 'phone': '09828230781', 'rating': '4.6', 'website': 'https://link.zomato.com/xqzv/rshare?id\\u003d19923423bdcb9b36'}
{'id': 22, 'name': 'Jodhpur Veg, Non-Veg & Fast Food Restaurant', 'url': 'https://www.google.com/maps/place/Jodhpur+Veg,+Non-Veg+%26+Fast+Food+Restaurant/data=!4m7!3m6!1s0x39418b772916c10b:0x4386c1efccbc07aa!8m2!3d26.2090485!4d73.0272835!16s%2Fg%2F11g30_q28t!19sChIJC8EWKXeLQTkRqge8zO_BhkM?authuser=0&hl=en&rclk=1', 'phone': '08239640772', 'rating': '3.9', 'website': nan}
{'id': 23, 'name': 'Acharya Rooftop Restaurant & Guest House', 'url': 'https://www.google.com/maps/place/Acharya+Rooftop+Restaurant+%26+Guest+House/data=!4m7!3m6!1s0x39418d637748c325:0x9da135c45a7add13!8m2!3d26.2981184!4d73.0211105!16s%2Fg%2F11tnnqbfq_!19sChIJJcNId2ONQTkRE916WsQ1oZ0?authuser=0&hl=en&rclk=1', 'phone': '09024077490', 'rating': '4.8', 'website': nan}
{'id': 24, 'name': 'Divyanshi The Taste Of Jodhpur Veg-Non Veg Restaurant', 'url': 'https://www.google.com/maps/place/Divyanshi+The+Taste+Of+Jodhpur+Veg-Non+Veg+Restaurant/data=!4m7!3m6!1s0x39418bcc3355a1a5:0xb6503b3beb38376d!8m2!3d26.2160158!4d73.0153581!16s%2Fg%2F11l5vh0cc_!19sChIJpaFVM8yLQTkRbTc46zs7ULY?authuser=0&hl=en&rclk=1', 'phone': '09636533777', 'rating': '4.5', 'website': 'https://www.swiggy.com/restaurants/the-taste-of-jodhpur-meera-nagar-basni-jodhpur-799435/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 25, 'name': 'Gypsy Vegetarian Restaurant', 'url': 'https://www.google.com/maps/place/Gypsy+Vegetarian+Restaurant/data=!4m7!3m6!1s0x39418d2be40d9b47:0xc82a0250d43fbf36!8m2!3d26.2751618!4d73.0077764!16s%2Fg%2F1td74zyg!19sChIJR5sN5CuNQTkRNr8_1FACKsg?authuser=0&hl=en&rclk=1', 'phone': '07412074075', 'rating': '4', 'website': nan}
{'id': 26, 'name': 'Kasturi Flavours Restaurant - Jodhpur', 'url': 'https://www.google.com/maps/place/Kasturi+Flavours+Restaurant+-+Jodhpur/data=!4m7!3m6!1s0x39418938220cc6d3:0x8e9dd95f27abadad!8m2!3d26.2223226!4d72.9686233!16s%2Fg%2F11fzfbswy8!19sChIJ08YMIjiJQTkRra2rJ1_ZnY4?authuser=0&hl=en&rclk=1', 'phone': '08094008357', 'rating': '4.7', 'website': 'https://www.kasturiorchid.com/our-restaurant/'}
{'id': 27, 'name': 'Kava Restaurant And Lounge - Fairfield by Marriott Jodhpur', 'url': 'https://www.google.com/maps/place/Kava+Restaurant+And+Lounge+-+Fairfield+by+Marriott+Jodhpur/data=!4m7!3m6!1s0x39418ba8c4821ee5:0xd26c660eb4d42929!8m2!3d26.2172753!4d73.0448635!16s%2Fg%2F11hgp1lrg5!19sChIJ5R6CxKiLQTkRKSnUtA5mbNI?authuser=0&hl=en&rclk=1', 'phone': '02917112222', 'rating': '4.1', 'website': 'https://www.marriott.com/hotels/hotel-information/restaurant/jdhfi-fairfield-jodhpur/'}
{'id': 28, 'name': 'ON THE FARM (OTF)', 'url': 'https://www.google.com/maps/place/ON+THE+FARM+%28OTF%29/data=!4m7!3m6!1s0x39418df1046db9e3:0xa9ec373a9c91c269!8m2!3d26.2644886!4d73.0593399!16s%2Fg%2F11qh2wqsr1!19sChIJ47ltBPGNQTkRacKRnDo37Kk?authuser=0&hl=en&rclk=1', 'phone': '07014295011', 'rating': '4.2', 'website': nan}
{'id': 29, 'name': 'Rigveda’ Jodhpur', 'url': 'https://www.google.com/maps/place/Rigveda%E2%80%99+Jodhpur/data=!4m7!3m6!1s0x39418c46dea1c0cd:0x7d5412512b88e751!8m2!3d26.2708648!4d73.0201595!16s%2Fg%2F11cnb89xpl!19sChIJzcCh3kaMQTkRUeeIK1ESVH0?authuser=0&hl=en&rclk=1', 'phone': '09314784000', 'rating': '4.4', 'website': 'https://www.swiggy.com/restaurants/rigveda-ratanada-basni-jodhpur-866880/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 30, 'name': "Hari Vedas' Jodhpur", 'url': 'https://www.google.com/maps/place/Hari+Vedas%27+Jodhpur/data=!4m7!3m6!1s0x39418c307664eaf9:0x2c7c6b5a19c2c869!8m2!3d26.2741545!4d73.0070067!16s%2Fg%2F11b67f3frf!19sChIJ-epkdjCMQTkRacjCGVprfCw?authuser=0&hl=en&rclk=1', 'phone': '02912444444', 'rating': '4.2', 'website': 'https://www.swiggy.com/restaurants/hari-vedas-sardarpura-basni-jodhpur-866802/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 31, 'name': 'Vegetrainian - The Train Restaurant', 'url': 'https://www.google.com/maps/place/Vegetrainian+-+The+Train+Restaurant/data=!4m7!3m6!1s0x39418d472a9ddfdb:0xc94c978068428e5e!8m2!3d26.2665463!4d73.0235491!16s%2Fg%2F11h4pcb9cq!19sChIJ29-dKkeNQTkRXo5CaICXTMk?authuser=0&hl=en&rclk=1', 'phone': '08905005600', 'rating': '4.3', 'website': 'https://www.swiggy.com/restaurants/vegetrainian-the-train-restaurant-sardarpura-new-jodhpur-jodhpur-513288/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 32, 'name': 'Ricotta', 'url': 'https://www.google.com/maps/place/Ricotta/data=!4m7!3m6!1s0x39418d0538500a97:0xc7ce032f95befc7e!8m2!3d26.2713891!4d73.0081135!16s%2Fg%2F11krhm6t16!19sChIJlwpQOAWNQTkRfvy-lS8Dzsc?authuser=0&hl=en&rclk=1', 'phone': '09352197529', 'rating': '4.7', 'website': 'https://www.swiggy.com/restaurants/ricotta-shastri-nagar-koramangala-jodhpur-1055698/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 33, 'name': 'Shree Subhadra hotel $ family restaurant', 'url': 'https://www.google.com/maps/place/Shree+Subhadra+hotel+$+family+restaurant/data=!4m7!3m6!1s0x39418bbcac3497df:0x3e7ea7eadf40c821!8m2!3d26.2138014!4d73.0285518!16s%2Fg%2F1hm22vqtd!19sChIJ35c0rLyLQTkRIchA3-qnfj4?authuser=0&hl=en&rclk=1', 'phone': '09829611960', 'rating': '4.1', 'website': nan}
{'id': 34, 'name': 'SAGA', 'url': 'https://www.google.com/maps/place/SAGA/data=!4m7!3m6!1s0x39418db7167277d9:0x599558aa5c4460d4!8m2!3d26.2708205!4d73.0302959!16s%2Fg%2F11h80dw6sx!19sChIJ2XdyFreNQTkR1GBEXKpYlVk?authuser=0&hl=en&rclk=1', 'phone': '08824688830', 'rating': '4.6', 'website': 'https://www.swiggy.com/restaurants/saga-ratanada-new-jodhpur-jodhpur-548990/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 35, 'name': 'Bungalow 12', 'url': 'https://www.google.com/maps/place/Bungalow+12/data=!4m7!3m6!1s0x39418dde1e2a49d7:0x3b1c3e7d5b012df4!8m2!3d26.2675243!4d73.0309974!16s%2Fg%2F11nxqyxdrl!19sChIJ10kqHt6NQTkR9C0BW30-HDs?authuser=0&hl=en&rclk=1', 'phone': '09828561212', 'rating': '4.4', 'website': 'https://www.instagram.com/bungalow.twelve/'}
{'id': 36, 'name': 'The Big "O" Restaurant and Lounge', 'url': 'https://www.google.com/maps/place/The+Big+%22O%22+Restaurant+and+Lounge/data=!4m7!3m6!1s0x39418fe00fab856b:0x6ba5c8f3c44d6a76!8m2!3d26.2449574!4d72.9737318!16s%2Fg%2F11fsk9k4wq!19sChIJa4WrD-CPQTkRdmpNxPPIpWs?authuser=0&hl=en&rclk=1', 'phone': '07568502020', 'rating': '4.1', 'website': 'https://www.swiggy.com/restaurants/the-big-o-restaurant-and-lounge-near-hp-petrol-pump-west-jodhpur-jodhpur-686551/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 37, 'name': 'Haldi Restaurant & Banquet Hall', 'url': 'https://www.google.com/maps/place/Haldi+Restaurant+%26+Banquet+Hall/data=!4m7!3m6!1s0x39418b7e0e0353e7:0xfe37b017b732c148!8m2!3d26.2370208!4d73.0100165!16s%2Fg%2F11sfbtw6r_!19sChIJ51MDDn6LQTkRSMEytxewN_4?authuser=0&hl=en&rclk=1', 'phone': '08769238369', 'rating': '4.4', 'website': 'https://www.zomato.com/jodhpur/haldi-restaurant-basni'}
{'id': 38, 'name': 'Gazania Restaurant', 'url': 'https://www.google.com/maps/place/Gazania+Restaurant/data=!4m7!3m6!1s0x39418d4ca1581d11:0x6731e7c01fbb87d2!8m2!3d26.2765089!4d73.0347203!16s%2Fg%2F11tdnk47gr!19sChIJER1YoUyNQTkR0oe7H8DnMWc?authuser=0&hl=en&rclk=1', 'phone': '07300009192', 'rating': '4.1', 'website': nan}
{'id': 39, 'name': 'Pet Pooja Veg & Non-veg restaurant', 'url': 'https://www.google.com/maps/place/Pet+Pooja+Veg+%26+Non-veg+restaurant/data=!4m7!3m6!1s0x39418b1bff20e36b:0x5ec827d0c561c0fd!8m2!3d26.2082163!4d73.025086!16s%2Fg%2F11rqxsf50r!19sChIJa-Mg_xuLQTkR_cBhxdAnyF4?authuser=0&hl=en&rclk=1', 'phone': '08003802957', 'rating': '5', 'website': nan}
{'id': 40, 'name': 'ZEEMLOGY RESTAURANT', 'url': 'https://www.google.com/maps/place/ZEEMLOGY+RESTAURANT/data=!4m7!3m6!1s0x39418d5e9c83aed1:0x7e21007009709f1a!8m2!3d26.2771007!4d73.0328628!16s%2Fg%2F11vdzvw6wc!19sChIJ0a6DnF6NQTkRGp9wCXAAIX4?authuser=0&hl=en&rclk=1', 'phone': '09929672219', 'rating': '4.6', 'website': 'https://www.swiggy.com/restaurants/zeemlogy-restaurant-ratanada-koramangala-jodhpur-1129095/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 41, 'name': 'DARBAARI - THE INDIAN GRILLS II BEST NON VEGETARIAN RESTAURANT', 'url': 'https://www.google.com/maps/place/DARBAARI+-+THE+INDIAN+GRILLS+II+BEST+NON+VEGETARIAN+RESTAURANT/data=!4m7!3m6!1s0x39418d000b0aec39:0xab8829ee69838410!8m2!3d26.2710068!4d73.0387964!16s%2Fg%2F11wg4zhwnt!19sChIJOewKCwCNQTkREISDae4piKs?authuser=0&hl=en&rclk=1', 'phone': nan, 'rating': '4.5', 'website': 'https://www.zomato.com/jodhpur/darbaari-the-indian-grills-1-ratanada/book?utm_source\\u003drwg'}
{'id': 42, 'name': 'THE SOLO HOUSE RESTAURANT', 'url': 'https://www.google.com/maps/place/THE+SOLO+HOUSE+RESTAURANT/data=!4m7!3m6!1s0x39418d001fdaf791:0x2fb039ccff4d1f7e!8m2!3d26.2712082!4d73.0291063!16s%2Fg%2F11m64vsc28!19sChIJkffaHwCNQTkRfh9N_8w5sC8?authuser=0&hl=en&rclk=1', 'phone': '08358005900', 'rating': '4.8', 'website': 'https://thesolohouseindia.com/'}
{'id': 43, 'name': 'Shree Balaji Restaurant', 'url': 'https://www.google.com/maps/place/Shree+Balaji+Restaurant/data=!4m7!3m6!1s0x39418b0652df413f:0x220d9c6dce23d1b7!8m2!3d26.205699!4d73.0151944!16s%2Fg%2F11k9jcxk6g!19sChIJP0HfUgaLQTkRt9Ejzm2cDSI?authuser=0&hl=en&rclk=1', 'phone': '08290739066', 'rating': '4.7', 'website': nan}
{'id': 44, 'name': 'Barbeque On Table', 'url': 'https://www.google.com/maps/place/Barbeque+On+Table/data=!4m7!3m6!1s0x39418ba59bde33bf:0x68dbfdc289912f62!8m2!3d26.2704395!4d73.0401234!16s%2Fg%2F11t2z0f4vg!19sChIJvzPem6WLQTkRYi-RicL922g?authuser=0&hl=en&rclk=1', 'phone': '09521677773', 'rating': '4.3', 'website': 'https://www.swiggy.com/restaurants/barbeque-on-table-defence-lab-road-new-jodhpur-jodhpur-708012/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}
{'id': 45, 'name': 'Baari restaurant', 'url': 'https://www.google.com/maps/place/Baari+restaurant/data=!4m7!3m6!1s0x39418da60e04df95:0xbe0cbc41916e80b4!8m2!3d26.3011601!4d73.0353292!16s%2Fg%2F11c31pn5_h!19sChIJld8EDqaNQTkRtIBukUG8DL4?authuser=0&hl=en&rclk=1', 'phone': '09660059488', 'rating': '4.6', 'website': 'https://www.swiggy.com/restaurants/baari-restaurant-and-lounge-paota-koramangala-jodhpur-1070904/dineout?is_retargeting\\u003dtrue\\u0026media_source\\u003dGoogleReserve\\u0026utm_campaign\\u003dGoogleMap\\u0026utm_source\\u003dGoogleReserve'}